github/codeql-go

change-notes/1.23/analysis-go.md
@max-schaefer. Thanks for adding some change notes. One typo and a couple of commas, otherwise looks great.
=> 1.23: SD-4095 Minor text changes to analysis change notes

ql/src/semmle/go/frameworks/SQL.qll
Ref: https://golang.org/pkg/database/sql/#Tx.ExecContext
=> Add sql.Tx.Exec/Query... support

ql/src/semmle/go/Expr.qll
Also change the doc comment on CharLit to RuneLit.
=> Add a RuneLit alias for CharLit

.github/workflows/codeqltest.yml
Could probably do with a Python script for setting up CodeQL, but this should do for now.
=> Add Action for testing using the CodeQL CLI

extractor/cli/go-autobuilder/go-autobuilder.go
A [distribution build](https://lgtm.com/admin/dist_builds/?create_time=1582207317507) on live showed no unexpected failures. Two projects that broke during the last distribution upgrade because their `make` build relies on headers that aren't installed are now back to working as well, since we override their build command to be just `go get`.
=> Ensure `LGTM_INDEX_BUILD_COMMAND` takes precedence over build-command guessing.

extractor/trap/trapwriter.go
As per Julian's note on slack.
=> extractor: Close files even when writes fail

CONTRIBUTING.md, README.md
Analogue to https://github.com/Semmle/ql/pull/3048.
=> Docs: Remove some Semmle references.

ql/src/semmle/go/frameworks/HTTP.qll, ql/src/semmle/go/frameworks/Stdlib.qll, ql/src/semmle/go/security/OpenUrlRedirectCustomizations.qll, ql/test/library-tests/semmle/go/frameworks/HTTP/UntrustedFlowSources.expected, ql/test/library-tests/semmle/go/frameworks/TaintSteps/TaintStep.expected, ql/test/library-tests/semmle/go/frameworks/TaintSteps/main.go
This just models quite a few more sources from HTTP request sources, as well as a step through `Read` methods.
[Evaluation](https://git.semmle.com/gist/sauyon/5ec280d3d4dd05c435e0c79f86fcb993) shows a few more results that look genuine.
=> HTTP Library Improvements

Makefile, ql/src/go.dbscheme.stats
[Evaluation](https://git.semmle.com/max/dist-compare-reports/blob/master/go/codeql-stats/report.md) (internal link) is unremarkable, suggesting that the changes to the stats probably didn't have too much effect on optimisation.
=> Use CodeQL for creating stats

ql/src/qlpack.yml, ql/test/qlpack.yml
Analogous to https://github.com/Semmle/ql/pull/3209.
=> Add extractor field to QL packs.

.github/workflows/codeqltest.yml
Required for the new set literal syntax for #113.
=> Use CodeQL version 2.1.1 for tests

ql/test/query-tests/Security/CWE-089/vendor/github.com/Masterminds/squirrel/LICENSE, ql/test/query-tests/filters/ClassifyFiles/vendor/github.com/onsi/ginkgo/LICENSE, ql/test/query-tests/filters/ClassifyFiles/vendor/github.com/onsi/gomega/LICENSE
=> Add license files for dependency stubs

change-notes/2020-05-07-update-data-flow.md, ql/src/semmle/go/dataflow/internal/DataFlowImpl.qll, ql/src/semmle/go/dataflow/internal/DataFlowImplCommon.qll, ql/test/query-tests/Security/CWE-089/SqlInjection.expected
https://github.com/Semmle/ql/pull/3020 and https://github.com/Semmle/ql/pull/3021
[Evaluation](https://git.semmle.com/max/dist-compare-reports/blob/master/go/update-data-flow/report.md) claims a slight speedup, but this is perhaps to be taken with a grain of salt:  a previous evaluation showed a minor overall slowdown.
=> Port recent data-flow improvements

change-notes/2020-05-13-io-model.md, ql/src/semmle/go/frameworks/Stdlib.qll
All changes are cosmetic.
cf #131.
=> Cleanup of `io` model

ql/src/experimental/CWE-807/SensitiveConditionBypassBad.go, ql/src/semmle/go/frameworks/NoSQL.qll, ql/test/library-tests/semmle/go/frameworks/NoSQL/main.go, ql/test/query-tests/Security/CWE-022/tst.go, ql/test/query-tests/Security/CWE-089/vendor/go.mongodb.org/mongo-driver/mongo/stub.go
Also includes a few drive-by fixes to the MongoDB model (apologies for the mission creep).
One of the fixes necessitated editing a generated library stub; I have filed an issue against depstubber about the underlyin problem.
=> Fix frontend errors in two tests and a code example

change-notes/2020-05-11-reflected-xss.md, ql/src/Security/CWE-601/BadRedirectCheck.ql, ql/src/semmle/go/Concepts.qll, ql/src/semmle/go/dataflow/SSA.qll, ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll, ql/src/semmle/go/frameworks/HTTP.qll, ql/src/semmle/go/frameworks/Macaron.qll, ql/src/semmle/go/frameworks/Stdlib.qll, ql/src/semmle/go/security/OpenUrlRedirectCustomizations.qll, ql/src/semmle/go/security/ReflectedXssCustomizations.qll, ql/test/query-tests/Security/CWE-079/ReflectedXss.expected, ql/test/query-tests/Security/CWE-079/tst.go
[Evaluation](https://git.semmle.com/sauyon/dist-compare-reports/tree/a0a2f5459cd2b2cba8a964f8a4a05593b6241ac0) (internal link) shows a few fixed false positives and no performance changes.
=> ReflectedXss improvements

ql/src/semmle/go/Types.qll
=> Clarify which types have a qualified name.

README.md
Tiny improvement to the readme. Part of https://github.com/github/semmle-docs/issues/100.
=> Link README.md to the CodeQL repo

README.md
=> Add links to the CodeQL CLI and LGTM.com

docs/language/learn-ql/go/ast-class-reference.rst
To match https://github.com/github/codeql/pull/3685
=> Update AST class reference

ql/src/semmle/go/dataflow/internal/DataFlowImpl.qll, ql/src/semmle/go/dataflow/internal/DataFlowPrivate.qll
cf https://github.com/github/codeql/pull/3657
[Evaluation](https://github.com/max-schaefer/dist-compare-reports/blob/master/go/update-data-flow/report.md) (internal link) shows no changes in results or performance.
=> Data flow: Allow nodes to be hidden from path explanations

ql/src/RedundantCode/CompareIdenticalValues.ql, ql/src/RedundantCode/UnreachableStatement.ql, ql/src/Security/CWE-022/TaintedPath.qhelp, ql/src/Security/CWE-798/HardcodedCredentials.ql, ql/src/experimental/CWE-807/SensitiveConditionBypass.qll, ql/src/semmle/go/Scopes.qll
fixes github/codeql-go-team#131
=> Use allow or allowlist instead of whitelist

change-notes/2020-06-17-reflected-xss-refinements.md, ql/src/semmle/go/security/ReflectedXssCustomizations.qll, ql/test/query-tests/Security/CWE-079/ReflectedXss.expected, ql/test/query-tests/Security/CWE-079/contenttype.go
I ran a [dist-compare](https://git.semmle.com/sauyon/dist-compare-reports/tree/f57df53cd0d9a3ece665b0151ec65c92b0e5e5a2#-gobad-redirect-check-for-kubernetes_47063891dd782835170f500a83f37cc98c3c1013-1) but it had (I hope) clearly bogus results, so I've started it again.
I'm putting this PR up anyway since it's a relatively minor change.
=> ReflectedXSS refinement

.github/codeql/codeql-config.yml, .github/workflows/codeql-analysis.yml
I mostly went with what the Wizard suggested, except for disabling the autobuild step (since we don't have any C++, C# or Java code in this repo) and explicitly selecting Go as the only language to analyse.
=> Set up Code Scanning

ql/src/semmle/go/dataflow/internal/DataFlowImpl.qll, ql/src/semmle/go/dataflow/internal/DataFlowImplCommon.qll, ql/src/semmle/go/dataflow/internal/DataFlowPrivate.qll
cf https://github.com/github/codeql/pull/3456
=> Data flow: Track precise types during field flow

ql/src/semmle/go/AST.qll, ql/src/semmle/go/Comments.qll, ql/src/semmle/go/Decls.qll, ql/src/semmle/go/Expr.qll, ql/src/semmle/go/Files.qll, ql/src/semmle/go/GoMod.qll, ql/src/semmle/go/PrintAst.qll, ql/src/semmle/go/Stmt.qll
As discussed with the C++ team.
=> Rename `describeQlClass` to `getAPrimaryQlClass`.

Makefile, ql/src/semmle/go/dataflow/internal/DataFlowImpl.qll, ql/src/semmle/go/dataflow/internal/DataFlowImplCommon.qll, ql/src/semmle/go/dataflow/internal/DataFlowPrivate.qll, ql/src/semmle/go/dataflow/internal/tainttracking1/TaintTrackingImpl.qll
Evaluation showed no performance regressions or result changes.
=> Update data-flow libraries

ql/src/semmle/go/Locations.qll
cf https://github.com/github/codeql/pull/3907
=> Port Location qldoc update.

docs/language/learn-ql/go/library-modeling-go.rst
@jf205 made some more editorial suggestions to this topic when we moved it into the main Sphinx project (https://github.com/github/codeql/pull/3888). 
cc @owen-mc
=> Docs: Editorial changes to library modeling topic

extractor/cli/go-autobuilder/go-autobuilder.go, extractor/cli/go-autobuilder/go-autobuilder_test.go
Also try to catch edge cases a bit better and improve logging slightly.
=> autobuilder: Don't try to determine import paths for file URLs

ql/src/experimental/CWE-327/InsecureRandomness.qhelp, ql/src/experimental/CWE-327/InsecureRandomness.ql, ql/src/experimental/CWE-327/InsecureRandomnessCustomizations.qll, ql/src/experimental/CWE-327/examples/Crypto.go, ql/src/experimental/CWE-327/examples/InsecureRandomness.go, ql/test/experimental/CWE-327/InsecureRandomness.expected, ql/test/experimental/CWE-327/InsecureRandomness.go, ql/test/experimental/CWE-327/InsecureRandomness.qlref
* Fixed some trailing whitespace
* Squashed commits
* Fixed commit message
* Removed an accidental whitespace-only change
Otherwise this is identical to https://github.com/github/codeql-go/pull/286
=> (admin) Slightly cleaned up version of Insufficient Randomness

ql/src/semmle/go/security/InsecureFeatureFlag.qll
This is a necessary fix for https://github.com/github/semmle-code/pull/37157.
=> remove reliance on InferredBinding

change-notes/2020-08-28-allocation-size-overflow-sanitizers.md
As requested in https://github.com/github/codeql-go/pull/296#issuecomment-682045687
=> Add change note for #296

ql/src/semmle/go/frameworks/XPath.qll, ql/src/semmle/go/security/XPathInjectionCustomizations.qll
=> Update XPathExpressionString to match the Range pattern

extractor/cli/go-extractor/go-extractor.go
=> extractor: Extract the working directory if no packages are passed

ql/src/Security/CWE-352/ConstantOauth2State.ql, ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll, ql/src/semmle/go/dataflow/internal/TaintTrackingUtil.qll, ql/src/semmle/go/security/SafeUrlFlowCustomizations.qll, ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionModelStep.ql
I seem to remember things like this occurring in more places than this, but I guess I was mistaken. Perhaps I'm just missing something...?
=> Add utility predicates to FunctionModel

ql/docs/experimental.md
=> Update links in ql/docs/experimental.md

Makefile, ql/src/semmle/go/dataflow/internal/DataFlowImpl.qll, ql/src/semmle/go/dataflow/internal/DataFlowImpl2.qll, ql/src/semmle/go/dataflow/internal/DataFlowImplCommon.qll, ql/test/query-tests/Security/CWE-089/SqlInjection.expected, ql/test/query-tests/Security/CWE-601/OpenUrlRedirect/OpenUrlRedirect.expected
dist-compare run shows no difference in results and no significant change in timings
=> Update dataflow libs 2

ql/src/semmle/go/dataflow/internal/DataFlowPrivate.qll
This was causing cockroach to fail to complete under distcompare, and as it turns out to take around an hour to execute what should usually be a 3-minute query on lgtm.com. Full distcompare now in progress.
=> Improve join order in `isUnreachableInCall`

ql/src/Security/CWE-681/IncorrectIntegerConversion.ql, ql/src/experimental/Unsafe/WrongUsageOfUnsafe.ql, ql/src/semmle/go/controlflow/ControlFlowGraphImpl.qll, ql/src/semmle/go/controlflow/IR.qll, ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll, ql/test/library-tests/semmle/go/dataflow/FlowSteps/LocalFlowStep.expected, ql/test/library-tests/semmle/go/dataflow/TypeAssertions/DataFlow.ql, ql/test/library-tests/semmle/go/dataflow/TypeAssertions/test.go
@max-schaefer would appreciate if you'd have a glance at this one -- it's pretty ugly, but it's the least bad option I could come up with
=> Add data-flow edge `from -> to` in the context `to, ok := from.(*Type)`

ql/src/semmle/go/Architectures.qll, ql/src/semmle/go/dataflow/FunctionInputsAndOutputs.qll, ql/src/semmle/go/dataflow/TaintTracking2.qll, ql/src/semmle/go/dataflow/internal/TaintTrackingUtil.qll, ql/src/semmle/go/frameworks/Revel.qll, ql/src/semmle/go/security/OpenUrlRedirectCustomizations.qll
=> Add docstrings to all public elements

change-notes/2020-08-27-protobufs.md, change-notes/2020-09-14-split-string-sanitizer.md
=> Add change notes for PRs that omitted them

change-notes/2020-11-11-stored-command.md, ql/src/Security/CWE-078/StoredCommand.go, ql/src/Security/CWE-078/StoredCommand.qhelp, ql/src/Security/CWE-078/StoredCommand.ql, ql/src/Security/CWE-078/StoredCommandGood.go, ql/src/semmle/go/security/StoredCommand.qll, ql/test/query-tests/Security/CWE-078/StoredCommand.expected, ql/test/query-tests/Security/CWE-078/StoredCommand.go, ql/test/query-tests/Security/CWE-078/StoredCommand.qlref
Built on top of #399 because it uses the stored xss sources.
=> Add stored command query

change-notes/2020-11-27-external-api.md, ql/src/Security/CWE-020/ExternalAPISinkExample.go, ql/src/Security/CWE-020/ExternalAPITaintStepExample.go, ql/src/Security/CWE-020/ExternalAPIsUsedWithUntrustedData.qhelp, ql/src/Security/CWE-020/ExternalAPIsUsedWithUntrustedData.ql, ql/src/Security/CWE-020/UntrustedDataToExternalAPI.qhelp, ql/src/Security/CWE-020/UntrustedDataToExternalAPI.ql, ql/src/Security/CWE-020/UntrustedDataToUnknownExternalAPI.qhelp, ql/src/Security/CWE-020/UntrustedDataToUnknownExternalAPI.ql, ql/src/Security/CWE-079/ReflectedXss.go, ql/src/semmle/go/frameworks/Logrus.qll, ql/src/semmle/go/frameworks/SQL.qll, ql/src/semmle/go/frameworks/Testing.qll, ql/src/semmle/go/frameworks/WebSocket.qll, ql/src/semmle/go/security/ExternalAPIs.qll
I have based this on the java version (cf. https://github.com/github/codeql/pull/3938).
=> Untrusted data flow to external API

ql/src/semmle/go/security/UnsafeUnzipSymlinkCustomizations.qll
This used to get the closest enclosing loops of all expressions; now it is restricted to those surrounding interesting expressions.
=> Unsafe-unzip-symlinks: reduce cost of `getAnEnclosingLoop`

.github/workflows/codeqltest.yml, ql/src/Security/CWE-327/InsecureTLS.ql, ql/src/semmle/go/Architectures.qll, ql/src/semmle/go/frameworks/Echo.qll, ql/src/semmle/go/frameworks/HTTP.qll, ql/src/semmle/go/frameworks/Revel.qll, ql/src/semmle/go/frameworks/SQL.qll, ql/src/semmle/go/frameworks/Testing.qll, ql/src/semmle/go/frameworks/XNetHtml.qll, ql/src/semmle/go/security/ExternalAPIs.qll
Also reformat code (the autoformatter has changed slightly)
=> Upgrade CI toolchain to CodeQL 2.4.0

ql/src/semmle/go/frameworks/Revel.qll, ql/src/semmle/go/security/ExternalAPIs.qll
This means we will find more things.
=> Use `implements` for interface methods

ql/src/Security/CWE-020/MissingRegexpAnchor.ql, ql/test/query-tests/Security/CWE-020/MissingRegexpAnchor/MissingRegexpAnchor.expected, ql/test/query-tests/Security/CWE-020/MissingRegexpAnchor/main.go
Fixes #439.
(First contribution here, open to all feedback)
=> Support more regexp anchors

change-notes/2020-08-27-protobufs.md, change-notes/2020-09-14-split-string-sanitizer.md, ql/src/semmle/go/Architectures.qll, ql/src/semmle/go/dataflow/FunctionInputsAndOutputs.qll, ql/src/semmle/go/dataflow/TaintTracking2.qll, ql/src/semmle/go/dataflow/internal/TaintTrackingUtil.qll, ql/src/semmle/go/frameworks/Revel.qll, ql/src/semmle/go/security/OpenUrlRedirectCustomizations.qll
Brings in missing change-notes and documentation.
=> Merge rc/1.26 back into `main`

.github/workflows/codeqltest.yml, ql/src/semmle/go/frameworks/BeegoOrm.qll, ql/src/semmle/go/frameworks/GoRestfulHttp.qll, ql/src/semmle/go/frameworks/K8sIoApimachineryPkgRuntime.qll, ql/src/semmle/go/frameworks/Revel.qll, ql/src/semmle/go/security/CleartextLoggingCustomizations.qll
Seems like the autoformatter has updated.
=> Autoformatter update

ql/test/library-tests/semmle/go/dataflow/GuardingFunctions/test.go
Negation doesn't appear to be handled correctly, so one
of the lines is marked as a false positive.
=> Add tests for guarding functions proxied by a variable

ql/src/semmle/go/security/TaintedPathCustomizations.qll
This is already done elsewhere.
=> Reuse existing class instead of repeating it

extractor/cli/go-extractor/go-extractor.go
=> Add -overlay to recognized go build flags

.github/workflows/check-change-note.yml
c.f. https://github.com/github/codeql/pull/5214
=> Actions: Add change note checker

.github/workflows/codeqltest.yml, Makefile, change-notes/2021-02-18-go-116.md, extractor/cli/go-autobuilder/go-autobuilder.go, go.mod, ql/src/semmle/go/frameworks/Stdlib.qll, ql/src/semmle/go/frameworks/stdlib/Io.qll, ql/src/semmle/go/frameworks/stdlib/IoFs.qll, ql/src/semmle/go/frameworks/stdlib/Os.qll, ql/src/semmle/go/security/StoredXssCustomizations.qll, ql/test/extractor-tests/go1.16/embed.expected, ql/test/extractor-tests/go1.16/embed.ql, ql/test/extractor-tests/go1.16/embeddedfile.go, ql/test/extractor-tests/go1.16/file, ql/test/library-tests/semmle/go/frameworks/StdlibTaintFlow/Io.go, ql/test/library-tests/semmle/go/frameworks/StdlibTaintFlow/IoFs.go, ql/test/library-tests/semmle/go/frameworks/StdlibTaintFlow/Os.go, ql/test/library-tests/semmle/go/frameworks/StdlibTaintFlow/test.ql, ql/test/query-tests/Security/CWE-079/StoredXss.expected, ql/test/query-tests/Security/CWE-079/stored.go
Excludes treating embedded files as a variable initialization.
=> Add preliminary support for go 1.16

.github/workflows/docs-review.yml
Same as https://github.com/github/codeql/pull/5363.
=> Actions: Fix comment that tags the Docs team

.github/workflows/check-change-note.yml
I think this is why it wasn't doing anything.
=> Fix change note checker

change-notes/2021-03-16-nethttp-updated.md, ql/src/semmle/go/frameworks/stdlib/NetHttp.qll
=> Add Transport.RoundTrip()

ql/src/semmle/go/Errors.qll, ql/src/semmle/go/Files.qll
=> Add a new diagnostics file class and use it for errors

ql/src/semmle/go/dataflow/internal/DataFlowImpl.qll, ql/src/semmle/go/dataflow/internal/DataFlowImpl2.qll, ql/src/semmle/go/dataflow/internal/DataFlowImplCommon.qll, ql/src/semmle/go/dataflow/internal/DataFlowPrivate.qll
As of 2021-05-12. Brings in https://github.com/github/codeql/pull/5773.
=> Sync data-flow libraries

ql/src/Summary/LinesOfCode.ql
Porting https://github.com/github/codeql/pull/5902 @rneatherway
=> Tag lines of code query

ql/src/Security/CWE-020/IncompleteHostnameRegexp.ql, ql/src/Security/CWE-020/IncompleteUrlSchemeCheck.ql, ql/src/Security/CWE-020/MissingRegexpAnchor.ql, ql/src/Security/CWE-020/SuspiciousCharacterInRegexp.ql, ql/src/Security/CWE-020/UntrustedDataToExternalAPI.ql, ql/src/Security/CWE-020/UntrustedDataToUnknownExternalAPI.ql, ql/src/Security/CWE-022/TaintedPath.ql, ql/src/Security/CWE-022/UnsafeUnzipSymlink.ql, ql/src/Security/CWE-022/ZipSlip.ql, ql/src/Security/CWE-078/CommandInjection.ql, ql/src/Security/CWE-078/StoredCommand.ql, ql/src/Security/CWE-079/ReflectedXss.ql, ql/src/Security/CWE-079/StoredXss.ql, ql/src/Security/CWE-089/SqlInjection.ql, ql/src/Security/CWE-089/StringBreak.ql, ql/src/Security/CWE-190/AllocationSizeOverflow.ql, ql/src/Security/CWE-209/StackTraceExposure.ql, ql/src/Security/CWE-295/DisabledCertificateCheck.ql, ql/src/Security/CWE-312/CleartextLogging.ql, ql/src/Security/CWE-327/InsecureTLS.ql, ql/src/Security/CWE-338/InsecureRandomness.ql, ql/src/Security/CWE-352/ConstantOauth2State.ql, ql/src/Security/CWE-601/BadRedirectCheck.ql, ql/src/Security/CWE-601/OpenUrlRedirect.ql, ql/src/Security/CWE-640/EmailInjection.ql, ql/src/Security/CWE-643/XPathInjection.ql, ql/src/Security/CWE-681/IncorrectIntegerConversion.ql, ql/src/Security/CWE-798/HardcodedCredentials.ql, ql/src/Security/CWE-918/RequestForgery.ql
Add `security-severity` metadata, similar to https://github.com/github/codeql/pull/6080
=> Add security-severity scores

ql/examples/snippets/deferinloop.ql
Required to use this query with the CodeQL CLI
=> Add @kind to deferinloop.ql

extractor/extractor.go, extractor/util/util.go
This reverts commit e5a2b6081d6f48c8a3496f4d953b73ed8ec90daf, reversing
changes made to ee893b252c49f9f4a651d0cf6e61aee4e3df72f9.
=> Revert "Merge pull request #554 from xhd2015/accelerate_go_list"

ql/lib/semmle/go/Decls.qll, ql/lib/semmle/go/security/IncorrectIntegerConversionLib.qll, ql/src/Security/CWE-322/InsecureHostKeyCallback.ql, ql/src/Security/CWE-352/ConstantOauth2State.ql, ql/src/experimental/CWE-327/CryptoLibraries.qll, ql/src/experimental/CWE-942/CorsMisconfiguration.ql
You got a few new ones [since the last time I did this](https://github.com/github/codeql-go/pull/586).
=> apply the implicit-this patch to the remaining go code

ql/src/experimental/CWE-327/WeakCryptoAlgorithm.ql
CWE-328: Use of Weak Hash, see https://cwe.mitre.org/data/definitions/328.html
I know this is only for an experimental query, but I was looking through all our code for doing these changes anyway.
=> Tag queries with CWE-328

.codeqlmanifest.json
This controls how the qlpacks' versions will change after a release.
=> Add version policies

ql/lib/semmle/go/Scopes.qll
Store information more naturally for built-in functions.
=> Refactor isVariadic helper functions

ql/lib/semmle/go/security/IncorrectIntegerConversionLib.qll, ql/test/query-tests/Security/CWE-681/IncorrectIntegerConversion.go
Fixes https://github.com/github/codeql-go/issues/717
=> Integer conversion should ignore type assertions

codeql-tools/tracing-config.lua
Depends on an internal PR to update the API.
=> Update Lua tracing config.
