github/codeql-go

- CONTRIBUTING.md
Switch the link to use parentheses instead of square brackets as it is an inline link as opposed to a reference-style link.
> Fix Code of Conduct link in CONTRIBUTING.md

- ql/src/semmle/go/security/StringBreakCustomizations.qll
- ql/test/query-tests/Security/CWE-089/StringBreak.expected
- ql/test/query-tests/Security/CWE-089/tst.go
`json.Marshal` returns two results, we only want to consider the first one as a source.
I have verified that we still flag the CVE I initially wrote this query for.
> Sharpen the sources for `StringBreak`.

- ql/src/semmle/go/dataflow/internal/DataFlowImpl.qll
- ql/src/semmle/go/dataflow/internal/DataFlowImplCommon.qll
- ql/src/semmle/go/dataflow/internal/DataFlowPrivate.qll
- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
- ql/test/library-tests/semmle/go/dataflow/CallGraph/main.go
This ports over the changes from https://github.com/Semmle/ql/pull/2769, https://github.com/Semmle/ql/pull/2631, https://github.com/Semmle/ql/pull/2872, and https://github.com/Semmle/ql/pull/2822.
The last commit fixes the performance regression on `aws-sdk-go` we observed on the latest LGTM distribution upgrade. It was caused by https://git.semmle.com/Semmle/go/pull/239 but went undetected since `aws-sdk-go` wasn't part of our default benchmark suite; I've added it now. To verify that the fix doesn't break the call graph I ran a query over all Go projects on LGTM.com to compare the new and the old implementation (https://lgtm.com/query/6747287448283805953/), which found that the new implementation gives additional call-graph edges of the kind shown in the test, but doesn't lose any …
> Port recent data-flow improvements

- ql/src/semmle/go/Decls.qll
- ql/src/semmle/go/Scopes.qll
- ql/src/semmle/go/controlflow/ControlFlowGraphImpl.qll
- ql/src/semmle/go/controlflow/IR.qll
- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
- ql/test/library-tests/semmle/go/dataflow/InterProceduralDataFlow/Test.expected
- ql/test/library-tests/semmle/go/dataflow/InterProceduralDataFlow/receivers.go
The data-flow library now treats the receiver as just another parameter... almost. It turns out that propagating flow through receivers can become very imprecise in the presence of virtual calls to megamorphic methods like `Error` and `String`. As a quick workaround, we disable receiver flow for virtual calls (as suggested by @sauyon). Ideally we'd handle this in a more principled fashion, for example by more precisely resolving virtual calls, but I've seen cases where it's not at all clear how one would do that.
Evaluation looks [very good](https://git.semmle.com/max/dist-compare-reports/blob/master/go/receiver-flow/report.md) (internal link), in fact it looks so good that I wouldn't set too much store by the reported performance improvements, and rather read it as confirmation that …
> Propagate data flow through receivers

- ql/src/semmle/go/Scopes.qll
Like-named fields declared in identical types are identical. This can be a little confusing, since such fields will have multiple declarations and multiple locations, so it's worth calling out explicitly in the documentation.
> Clarify field identity

- .gitattributes
Also only add attributes to go files under the ql directory.
Thought I'd make this PR since it doesn't really make sense to wait for go.mod extraction to be merged (or really for this change to be a part of it...).
> .gitattributes: Use -text instead of binary

- Makefile
We don't track dependencies for the extractor, but instead rely on the Go compiler's caching to be fast enough that we can afford to just rebuild every time. But this means that make can't really know when the extractor is out of date, so I think we should mark all extractor-related targets as phony.
> Make extractor targets phony.

- Makefile
This fixes `make test` sometimes failing because of remaining state in `build/testdb`.
> Makefile: make testdb target phony

- extractor/dbscheme/tables.go
- ql/src/go.dbscheme
- ql/src/semmle/go/Scopes.qll
- upgrades/ffced433fce33521f90c1b6c66b611902cdceac2/go.dbscheme
This fixes an oversight in #41: methods can be associated with more than one named type, so the first column of `methodhosts` isn't unique. (Thanks to @sauyon for noticing and diagnosing the root cause!)
Since the upgrade to the dbscheme is still the last one, I chose to fix it in-place instead of adding another upgrade script.
Initial sanity checking looks good, but I'm running a full dist-compare to make sure.
> Remove a mistaken uniqueness annotation.

- extractor/trap/trapwriter.go
Found via profiling that the vast majority of the time taken during extraction was `write` syscalls.
This empirically makes things much faster on Kubernetes, n=1:
Before:
1481.40s user 996.60s system 282% cpu 14:36.62 total
After:
606.63s user 12.59s system 338% cpu 3:02.91 total
Was there a reason we were running `Sync` before? My understanding is that it's not  necessary unless we want trap files to be uncorrupted if the system crashes.
I've kicked off an evaluation.
> Use bufio and don't sync FS

- ql/src/semmle/go/dataflow/FunctionInputsAndOutputs.qll
- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
- ql/src/semmle/go/dataflow/internal/TaintTrackingUtil.qll
- ql/src/semmle/go/frameworks/Stdlib.qll
- ql/test/library-tests/semmle/go/dataflow/FlowSteps/LocalFlowStep.expected
- ql/test/library-tests/semmle/go/dataflow/FlowSteps/LocalTaintStep.expected
- ql/test/library-tests/semmle/go/dataflow/FlowSteps/main.go
We've previously found ourselves wanting `FunctionOutput`s that cover "output parameters". While there isn't such a concept in Go, for taint propagation we nevertheless may want to think about certain functions as propagating taint "into" one of their parameters. One example is the built-in `copy` function, which propagates taint from its second parameter to its first.
This PR adds support for that kind of function output, and adds a model for `copy` (as well as for `append` which we previously were missing). I also noticed that our standard taint steps weren't properly distinguishing addition from string concatenation (first commit), and that our data-flow steps for global functions were pointing in the wrong direction :man_facepalming:, which is fixed in the last commit. …
> Make `FunctionOutput` more useful

- ql/src/semmle/go/Concepts.qll
- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
- ql/src/semmle/go/dataflow/internal/TaintTrackingUtil.qll
- ql/src/semmle/go/frameworks/Stdlib.qll
- ql/src/semmle/go/security/StringBreakCustomizations.qll
- ql/test/query-tests/Security/CWE-089/SqlInjection.expected
- ql/test/query-tests/Security/CWE-089/issue48.go
- ql/test/query-tests/Security/CWE-089/tst.go
Fixes #48.
There are three fairly orthogonal changes in the first three commits:
- Modeling of marshaling and unmarshaling functions, instantiated for the particular case of `encoding/json`.
- Better taint-tracking through pointers, especially in the presence of function models. In particular, if we pass an address expression `&p` to a function in a position that we know gets tainted, we can taint the underlying value `p`. (Obviously not something we want to do for general data flow.)
- Taint model of `ioutil.ReadAll`.
The last two commits add test cases.
[Evaluation](https://git.semmle.com/max/dist-compare-reports/blob/master/go/issue-48/report.md) was entirely uneventful.
> Improve taint-tracking through pointers and other fixes

- change-notes/1.24/extractor-go.md
- extractor/cli/go-autobuilder/go-autobuilder.go
I'm also going to run a test for disabling the dependency installation step if the file exists, as in theory that should help with performance.
If I were to add another environment variable to customize that behavior should I use the `LGTM` or `CODEQL` prefix?
> extractor: Use -mod=vendor when a vendor directory exists

- extractor/extractor.go
I noticed Kubernetes was constantly complaining there was no label for methods, which seems strange, given that the underlying type *should* have been extracted already. I'm looking into why this is the case, but for now it seems like it's a good idea to just extract the method if its label doesn't exist.
> Extract methods when they don't exist

- extractor/trap/labels.go
- extractor/trap/trapwriter.go
This reduces the total size of TRAP files, in many cases dramatically so (kubernetes: 13G -> 2G, cockroach: 6.5G -> 1.2G, aws-sdk-go: 2.9G -> 557M), at the cost of slowing down extraction in some cases (kubernetes: 606s -> 727s, but cockroach: 376s -> 368s, aws-sdk-go: 223s -> 183s). More data is [here](https://docs.google.com/spreadsheets/d/1Z-vqhVwn_iFIO0_1z49WPwf2KlLP3qWiyFnR5X4g7Io) (internal link); note that the timings are probably less reliable than usual since they were taken on my laptop.
In spite of the potential slowdown I think this is worth it, since TRAP size looks like a blocker for code scanning.
[Evaluation](https://git.semmle.com/max/dist-compare-reports/blob/master/go/trap.gz/report.md) (also internal link) is uneventful.
> Gzip TRAP files

- change-notes/1.24/analysis-go.md
- ql/src/Security/CWE-190/AllocationSizeOverflow.go
- ql/src/Security/CWE-190/AllocationSizeOverflow.qhelp
- ql/src/Security/CWE-190/AllocationSizeOverflow.ql
- ql/src/Security/CWE-190/AllocationSizeOverflowGood.go
- ql/src/semmle/go/security/AllocationSizeOverflow.qll
- ql/src/semmle/go/security/AllocationSizeOverflowCustomizations.qll
- ql/test/query-tests/Security/CWE-190/AllocationSizeOverflow.expected
- ql/test/query-tests/Security/CWE-190/AllocationSizeOverflow.go
- ql/test/query-tests/Security/CWE-190/AllocationSizeOverflow.qlref
- ql/test/query-tests/Security/CWE-190/AllocationSizeOverflowGood.go
- ql/test/query-tests/Security/CWE-190/AllocationSizeOverflowGood2.go
- ql/test/query-tests/Security/CWE-190/stubs.go
- ql/test/query-tests/Security/CWE-190/tst.go
- ql/test/query-tests/Security/CWE-190/tst2.go
The query flags arithmetic (specifically addition and multiplication) involving quantities derived from the size of a potentially large object (specifically a JSON-encoded value or file-system data), where the result of the operation is subsequently used in an allocation. If the operation overflows (for signed types), the allocation will panic; if it wraps (for unsigned types), too little space will be allocated.
I chose to only model this fairly restrictive case because a more general arithmetic-overflow query is likely to be quite noisy (the ones for C++ and Java apparently are). Being able to point to the allocation where the potentially overflowing value is used makes the results more concrete.
An [evaluation](https://git.semmle.com/max/dist-compare-reports/blob/master/go/tainted-arith …
> Add new query `AllocationSizeOverflow`.

- change-notes/1.24/analysis-go.md
- ql/src/InconsistentCode/MistypedExponentiation.ql
- ql/test/query-tests/InconsistentCode/MistypedExponentiation/main.go
> MistypedExponentiation: Add a heuristic to reduce FPs

- .codeqlmanifest.json
- Makefile
As suggested by Pavel. I believe it removes the need for the `--additional-packs` argument to the test command, did you want that for any other reason?
> Add examples qlpack.yml to CodeQL manifest

- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
- ql/src/semmle/go/dataflow/internal/TaintTrackingUtil.qll
- ql/test/library-tests/semmle/go/dataflow/FlowSteps/LocalTaintStep.expected
- ql/test/library-tests/semmle/go/frameworks/TaintSteps/TaintStep.expected
- ql/test/query-tests/Security/CWE-079/ReflectedXss.expected
- ql/test/query-tests/Security/CWE-079/tst.go
This adds a taint step from `pred` to (the post-update node) of `succ` in `succ[idx] = pred` and its syntactic variants.
Unlike for structs, where partially tainted values are quite common, the theory is that arrays, maps, and slices are usually either completely tainted or completely clean.
[Evaluation](https://git.semmle.com/max/dist-compare-reports/blob/master/go/issue-72/report.md) is mostly clean, except for a very curious new result on `cockroach` from a completely unrelated query in generated code. The alert is a true positive, the file in question just doesn't exist in the previous version. My guess is that it's a non-deterministic build, though this is the first time I'm seeing this for `cockroach`.
> Track taint through element writes.

- ql/src/experimental/Security/CWE-643/XPathInjection.go
- ql/src/experimental/Security/CWE-643/XPathInjection.qhelp
- ql/src/experimental/Security/CWE-643/XPathInjection.ql
An XPath injection query is available for C#, JavaScript, Java but not for Go.
This pull request consist of an XPath Injection query to detect cases in which user input is used unsafely included in an XPath query.
I'm pretty much new to the Go language, so I hope my example code works.
I'm also new to the Go QL flavour so I've added a TODO which I'm currently not sure how to solve.
Query help is inspired/ported from the C# query help.
Code will be autoformatted soon.
> CWE-643 XPathInjection on Go

- ql/src/experimental/RequestForgery/RequestForgery.ql
- ql/src/experimental/RequestForgery/RequestForgery.qll
- ql/src/experimental/RequestForgery/RequestForgeryCustomizations.qll
- ql/src/semmle/go/Concepts.qll
- ql/src/semmle/go/frameworks/HTTP.qll
In commit order, this PR:
- Adds an `HTTP::ClientRequest` class and module to the `Concepts` library, to model APIs that make HTTP requests.
- Models HTTP request functions in the `net/http` package, as a concrete instance of the above concept.
- Uses the above library changes to add a query for request forgery (SSRF), tracking tainted data from untrusted input to the URL used in an HTTP request. This is ported from the corresponding query for JavaScript, though currently limited in scope. It includes companion libraries for customisation (which will need to be moved into the libraries if we decide to publish this query).
- Adds a simple sanitiser edge: consider a URL string sanitised if the hostname cannot be controlled.
I have used this to find results on customer code, but have not yet …
> Add experimental query for request forgery.

- change-notes/1.24/analysis-go.md
- ql/src/semmle/go/frameworks/HTTP.qll
- ql/src/semmle/go/frameworks/Stdlib.qll
- ql/src/semmle/go/security/OpenUrlRedirect.qll
- ql/src/semmle/go/security/OpenUrlRedirectCustomizations.qll
- ql/test/library-tests/semmle/go/frameworks/HTTP/UntrustedFlowSources.expected
- ql/test/query-tests/Security/CWE-089/SqlInjection.expected
- ql/test/query-tests/Security/CWE-601/OpenUrlRedirect/OpenUrlRedirect.expected
- ql/test/query-tests/Security/CWE-601/OpenUrlRedirect/stdlib.go
Tested this on LGTM.com and it fixes all but two of the obvious false positives.
The last two are [these](https://lgtm.com/projects/g/caddyserver/caddy/snapshot/89b6c8ef3926b30ed1b8dca64f8ebd3301c9321f/files/caddyhttp/staticfiles/fileserver.go?sort=name&dir=ASC&mode=heatmap#xf26e02affcbaab40:1) [results](https://lgtm.com/projects/g/caddyserver/caddy/snapshot/89b6c8ef3926b30ed1b8dca64f8ebd3301c9321f/files/caddyhttp/staticfiles/fileserver.go?sort=name&dir=ASC&mode=heatmap#xc9a7505ef87e05cd:1) on `caddyserver/caddy`, for which the source, which I'd expect to be on line 102 of `fileserver.go`, is strangely not found. I'll probably do some digging into this eventually, but I thought I'd leave it here for now since it seems like this may be a bit more involved.
> OpenUrlRedirect: Expand safe URL flow configuration

- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
- ql/src/semmle/go/dataflow/internal/TaintTrackingUtil.qll
- ql/src/semmle/go/dataflow/internal/tainttracking1/TaintTrackingImpl.qll
Apart from a missing module doc comment for `TaintTrackingImpl.qll` which we'll need to synchronize with the other languages (https://github.com/Semmle/ql/pull/3155), this gets us to 100% Qldoc coverage.
> Add Qldoc for the last few remaining predicates.

- change-notes/1.24/extractor-go.md
- extractor/cli/go-autobuilder/go-autobuilder.go
We've occasionally had to tell people to set this variable manually, so we might as well have an alias that doesn't refer to a soon-to-be obsolete product.
> Introduce `CODEQL_GO_EXTRACTOR_BUILD_COMMAND` as an alias for `LGTM_INDEX_BUILD_COMMAND`.

- change-notes/1.24/extractor-go.md
- extractor/cli/go-autobuilder/go-autobuilder.go
- extractor/extractor.go
- extractor/util/util.go
We've had to tell people how to do this, so we should have a name for it that doesn't refer to a defunct company.
> Introduce official environment variable for goroutine limiting.

- ql/src/codeql-suites/go-code-scanning.qls
This is the suite that'll be run by default for the code-scanning feature.
Also see https://github.com/Semmle/ql/pull/3163 for the definition of `code-scanning-selectors.yml`.
> Add code-scanning suites

- extractor/cli/go-extractor/go-extractor.go
Might as well have these in master; they are intentionally undocumented for now.
I switched from command-line arguments to environment variables because they are easier to thread through the autobuilder.
> Add environment variables for dumping CPU and memory profiles.

- change-notes/1.24/analysis-go.md
- ql/src/Security/CWE-295/DisabledCertificateCheck.ql
- ql/src/filters/ClassifyFiles.ql
- ql/src/semmle/go/frameworks/Testing.qll
- ql/test/query-tests/filters/ClassifyFiles/ClassifyFiles.expected
- ql/test/query-tests/filters/ClassifyFiles/TestCase.expected
- ql/test/query-tests/filters/ClassifyFiles/TestCase.ql
- ql/test/query-tests/filters/ClassifyFiles/httptest.go
- ql/test/query-tests/filters/ClassifyFiles/test1.go
I've only added tests for one of them, which is part of the standard library. The others might be good test cases for the stubber.
> Recognise more testing frameworks

- ql/test/library-tests/semmle/go/dataflow/FlowSteps/LocalFlowStep.expected
- ql/test/library-tests/semmle/go/dataflow/FlowSteps/main.go
- ql/test/query-tests/InconsistentCode/MistypedExponentiation/main.go
- ql/test/query-tests/RedundantCode/DeadStoreOfLocal/DeadStoreOfLocal.expected
- ql/test/query-tests/RedundantCode/DeadStoreOfLocal/testdata.go
- ql/test/query-tests/Security/CWE-190/AllocationSizeOverflowGood2.go
- ql/test/query-tests/Security/CWE-295/DisabledCertificateCheck/tst.go
This fixes all (unintentional) errors not covered by https://github.com/github/codeql-go/pull/96.
> Fix a few compiler errors in tests

- change-notes/1.24/analysis-go.md
- change-notes/1.24/extractor-go.md
Covering https://github.com/github/codeql-go/pull/57 and https://github.com/github/codeql-go/pull/69.
> Add two missing change notes.

- extractor/extractor.go
- ql/src/semmle/go/Errors.qll
- ql/test/consistency/UnexpectedFrontendErrors.ql
- ql/test/consistency/test.go
- ql/test/library-tests/semmle/go/Types/SignatureType_getNumParameter.expected
- ql/test/library-tests/semmle/go/Types/SignatureType_getNumResult.expected
- ql/test/library-tests/semmle/go/Types/notype.expected
- ql/test/library-tests/semmle/go/Types/unknownFunction.go
- ql/test/query-tests/RedundantCode/DeadStoreOfLocal/DeadStoreOfLocal.expected
- ql/test/query-tests/RedundantCode/DeadStoreOfLocal/main.go
- ql/test/query-tests/RedundantCode/ImpossibleInterfaceNilCheck/err.go
CodeQL does not support consistency queries yet, but I have verified that it works as expected with `odasa qltest`.
> Add consistency query flagging tests with unexpected frontend errors

- ql/src/semmle/go/dataflow/FunctionInputsAndOutputs.qll
- ql/src/semmle/go/dataflow/internal/DataFlowPrivate.qll
- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionInput_getEntryNode.expected
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionInput_getExitNode.expected
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionModelStep.expected
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionModelStep.ql
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionOutput_getExitNode.expected
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/tst.go
It was broken because it relied on `ArgumentNode.argumentOf`, which doesn't consider receivers of functions without a body (such as interface methods or native methods) to avoid imprecise inter-procedural flow. While that is something we should fix properly in the long run, working around it by using a lower-level predicate is easy.
As shown by the test, this makes function models that model flow into the receiver work again.
[Evaluation](https://git.semmle.com/max/dist-compare-reports/blob/master/go/receiver-output/report.md) shows no performance regressions or result changes, so I don't think we need a change note for this.
> Fix `getExitNode` for receiver outputs.

- ql/src/experimental/CWE-640/EmailInjection.qhelp
- ql/src/experimental/CWE-640/EmailInjectionCustomizations.qll
- ql/src/semmle/go/frameworks/Email.qll
- ql/test/library-tests/semmle/go/frameworks/Email/MailData.ql
cf https://github.com/github/codeql-go/pull/108
cc @porcupineyhairs
> Clean up `EmailInjection.qll` and related libraries.

- ql/src/codeql-suites/go-lgtm-full.qls
- ql/src/localDefinitions.ql
- ql/src/localReferences.ql
This enables jump-to-definition and find-references in the VS Code
extension, for golang source archives.
> Add queries for ide search.

- ql/src/experimental/CWE-840/ConditionBypass.qhelp
- ql/src/experimental/CWE-840/ConditionBypass.ql
- ql/src/experimental/CWE-840/ConditionBypassBad.go
- ql/src/experimental/CWE-840/ConditionBypassGood.go
- ql/test/experimental/CWE-840/ConditionBypass.expected
- ql/test/experimental/CWE-840/ConditionBypass.qlref
- ql/test/experimental/CWE-840/condition.go
This is a comparatively simpler query. 
This is inspired from the following code snippet which was found in [Gorillas websocket](https://www.gorillatoolkit.org/pkg/websocket#Upgrade) package documentation.
```go
if req.Header.Get("Origin") != "http://"+req.Host {
http.Error(w, "Origin not allowed", http.StatusForbidden)
return
}
```
Here, the comparison is between two attacker controlled fields and hence, the check can effectively be bypassed. 
Since, this has been done once and I can already see some instances on Github's fuzzy search where this is found, it makes sense to add this to the default set of queries.
> User-controlled bypass of a comparision

- change-notes/2020-05-12-tainted-path.md
- ql/src/semmle/go/frameworks/Stdlib.qll
- ql/test/query-tests/Security/CWE-022/TaintedPath.expected
- ql/test/query-tests/Security/CWE-022/ZipSlip.expected
- ql/test/query-tests/Security/CWE-022/tst.go
[Evaluation](https://git.semmle.com/sauyon/dist-compare-reports/tree/917c7ae7b9fc276befaf4b1d0b202ced1d848e32) is clean apart from the sourcegraph false positives, which I've opened an issue for.
> Add support for ioutil TempFile and TempDir

- ql/src/semmle/go/frameworks/Stdlib.qll
- ql/test/library-tests/semmle/go/frameworks/TaintSteps/TaintStep.expected
- ql/test/library-tests/semmle/go/frameworks/TaintSteps/io.go
This PR models the golang stdlib io package. It depends on #129.
Here's a brief of changes made. 
1. I have moved `Reader.Read`,`Writer.Write`, `WriteString` which Max wrote in #129 into a new `IO.qll` file. I have also added a few doc comments on them.
1. I have further modelled multiple function definitions found in the `io` package. From what I can see, this completes the entire package.
1. I am yet to add tests but I would like a review before that.
Also, please note that I have based my PR on #129. Since, the PR is not yet merged, you may have to cherry-pick the commits before merging.
> Model stdlib's IO package.

- ql/src/experimental/CWE-807/SensitiveConditionBypass.qhelp
- ql/src/experimental/CWE-807/SensitiveConditionBypass.ql
- ql/src/experimental/CWE-807/SensitiveConditionBypass.qll
- ql/src/experimental/CWE-807/SensitiveConditionBypassBad.go
- ql/test/experimental/CWE-807/SensitiveConditionBypass.expected
- ql/test/experimental/CWE-807/SensitiveConditionBypass.qlref
- ql/test/experimental/CWE-807/SensitiveConditionBypassBad.go
- ql/test/experimental/CWE-807/condition.go
This PR adds test for the following type of code.
```go
func ex3(w http.ResponseWriter, r *http.Request) {
test2 := "test"
if r.Header.Get("X-Password") != test2 {
login()
}
}
```
This throws an alert when an untrusted input is checked against a constant value and that test is guarding a sensitive action such as a `login call`.
In the current form, the query does not implement any `BarrierGuard`s. I do have a few in mind but I would like to see the results of this query run on all LGTM projects. As most of them will also filter out actual positive results.
> User-controlled bypass of sensitive action

- ql/src/semmle/go/Scopes.qll
- ql/test/library-tests/semmle/go/Scopes/DeclaredEntity.expected
- ql/test/library-tests/semmle/go/Scopes/EntityReference.expected
- ql/test/library-tests/semmle/go/Scopes/EntityType.expected
- ql/test/library-tests/semmle/go/Scopes/MethodImplements.expected
- ql/test/library-tests/semmle/go/Scopes/MethodImplements.ql
- ql/test/library-tests/semmle/go/Scopes/MethodImplementsName.expected
- ql/test/library-tests/semmle/go/Scopes/MethodImplementsName.ql
- ql/test/library-tests/semmle/go/Scopes/Methods.expected
- ql/test/library-tests/semmle/go/Scopes/TypeImplements.expected
- ql/test/library-tests/semmle/go/Scopes/types.go
- ql/test/query-tests/Security/CWE-079/ReflectedXss.expected
- ql/test/query-tests/Security/CWE-079/tst.go
Without this restriction, the two `m`s in the following example are considered to implement each other, even though they aren't logically related:
```go
type I interface {
m()
}
type J interface {
m()
}
type K struct {
I
J
}
```
Previously, interface methods would sometimes implement themselves and sometimes not (see changes to test output for examples).
An [evaluation](https://git.semmle.com/max/dist-compare-reports/blob/master/go/interface-method-implements/report.md) shows no result changes. Performance seems to overall have become slightly worse (note that the large-ish relative slowdowns are on very small projects and hence small in absolute terms), but looking at the performance profiles I couldn't see anything sticking out, so I'm inclined to mostly blame this on experimental …
> Refine `Method.implements` so that interface methods only implement themselves.

- ql/src/semmle/go/security/AllocationSizeOverflowCustomizations.qll
Looking for expressions that may be big is simpler than looking for expressions that may be small, and while there can be more of the former than the latter, it is overall still [a win](https://git.semmle.com/max/dist-compare-reports/blob/master/go/allocation-size-is-big/report.md) on big projects (note that the timings are just for this one query, hence the occasional zero-second column).
> Simplify logic in AllocationSizeOverflow query.

- change-notes/2020-05-18-redundant-recover.md
- ql/src/RedundantCode/RedundantRecover.qhelp
- ql/src/RedundantCode/RedundantRecover.ql
- ql/src/RedundantCode/RedundantRecover1.go
- ql/src/RedundantCode/RedundantRecover1Good.go
- ql/src/RedundantCode/RedundantRecover2.go
- ql/src/RedundantCode/RedundantRecover2Good.go
- ql/test/query-tests/RedundantCode/RedundantRecover/RedundantRecover.expected
- ql/test/query-tests/RedundantCode/RedundantRecover/RedundantRecover.qlref
- ql/test/query-tests/RedundantCode/RedundantRecover/RedundantRecover1.go
- ql/test/query-tests/RedundantCode/RedundantRecover/RedundantRecover1Good.go
- ql/test/query-tests/RedundantCode/RedundantRecover/RedundantRecover2.go
- ql/test/query-tests/RedundantCode/RedundantRecover/RedundantRecover2Good.go
- ql/test/query-tests/RedundantCode/RedundantRecover/tst.go
It's very easy to think you are using `recover` correctly when you aren't. The two patterns I've found are (a) deferring a call to `recover` directly, (b) not deferring the call to `recover` and (c) deferring a function which calls a function which calls recover - the panic doesn't propagate down the stack, only back up it. This query finds direct calls to recover and calls to recover in functions which are never called in a defer statement (but which are called at least once). I haven't done a perfomance comparison.
> Go: Add query for redundant calls to recover

- .gitignore
I accidentally added this while testing some time ago.
Should we remove this from our history?
I've also added the name `main` to the gitignore.
> Remove accidentally committed binary

- Makefile
- ql/src/semmle/go/dataflow/internal/DataFlowImpl.qll
- ql/src/semmle/go/dataflow/internal/tainttracking1/TaintTrackingImpl.qll
> Data flow: Remove deprecated predicates.

- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionInput_getEntryNode.expected
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionInput_getExitNode.expected
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionModelStep.expected
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionModelStep.ql
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionOutput_getEntryNode.expected
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionOutput_getExitNode.expected
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/reset.go
To model (taint) flow through functions, we introduce post-update nodes for arguments (including receivers) to represent the potentially updated value of the argument after the call, but only if that argument is mutable.
However, previously our criterion for determining whether an argument is mutable was a little too restrictive. In particular, we would not consider a struct-typed argument as mutable, since structs are passed by value. While this is reasonable for data flow, it is unnecessarily restrictive for taint, since it makes perfect sense to track deep taint through structs.
So instead we now turn things round and instead consider _all_ types to be mutable except for primitive types (booleans, numbers, and strings).
An [evaluation](https://github.com/max-schaefer/dist-compare-report …
> Broaden definition of mutable types for taint tracking

- change-notes/2020-05-29-open-redirect.md
- ql/src/semmle/go/security/OpenUrlRedirectCustomizations.qll
- ql/test/query-tests/Security/CWE-601/OpenUrlRedirect/OpenUrlRedirect.expected
- ql/test/query-tests/Security/CWE-601/OpenUrlRedirect/stdlib.go
Despite its name, this method doesn't just handle form values but also query parameters.
Fixes https://github.com/github/codeql-go-team/issues/108.
> Consider `Request.FormValue(...)` as a source for URL redirects.

- ql/src/experimental/frameworks/Gin.qll
- ql/src/semmle/go/dataflow/FunctionInputsAndOutputs.qll
- ql/src/semmle/go/dataflow/internal/DataFlowPrivate.qll
- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
- ql/src/semmle/go/frameworks/Stdlib.qll
- ql/src/semmle/go/security/ReflectedXssCustomizations.qll
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionInput_getEntryNode.expected
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionOutput_getExitNode.expected
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionOutput_isResult.expected
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionOutput_isResult.ql
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionOutput_isResult_int.expected
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionOutput_isResult_int.ql
- ql/test/library-tests/semmle/go/dataflow/Nodes/BinaryOperationNodes.expected
- ql/test/library-tests/semmle/go/dataflow/Nodes/CallNode.expected
- ql/test/library-tests/semmle/go/dataflow/Nodes/CallNode_getArgument.expected
- ql/test/library-tests/semmle/go/dataflow/Nodes/CallNode_getResult.expected
- ql/test/library-tests/semmle/go/dataflow/Nodes/CallNode_getResult.ql
- ql/test/library-tests/semmle/go/dataflow/Nodes/CallNode_getResult_int.expected
- ql/test/library-tests/semmle/go/dataflow/Nodes/CallNode_getResult_int.ql
- ql/test/library-tests/semmle/go/dataflow/Nodes/main.go
Resolves #146 
Note that `FunctionOutput.isResult()` and `CallNode.getResult()` do not match anything when there is more than one result. I think this is less confusing and error-prone than the alternative.
> Make FunctionOutput.isResult(0) and CallNode.getResult(0) match single results

- ql/src/codeql-suites/go-security-and-quality.qls
- ql/src/codeql-suites/go-security-extended.qls
We want to add more code scanning query suites so that users to easily choose to run a larger set of query in a fully supported and maintainable way. We also don't want people to have to use the lgtm suites because it's an old product name that people shouldn't have to know about.
Suite names and contents were decided upon by @jhutchings1 and @sj.
See https://github.com/github/codeql/pull/3596 for more info
> Add more code-scanning suites

- .github/workflows/codeqltest.yml
- Makefile
- ql/src/semmle/go/Comments.qll
- ql/src/semmle/go/Expr.qll
- ql/src/semmle/go/Stmt.qll
- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
Use
```sh
make autoformat
```
to format all `.ql` and `.qll` files under `ql/src`.
Use
```sh
make AUTOFORMAT=--check-only autoformat
```
to check that all `.ql` and `.qll` files under `ql/src` are correctly formatted and fail if they are not.
The second commit adds a PR check to ensure everything is autoformatted. This is currently expected to fail; let's see whether it does. (**EDIT**: It does.)
> Add Make target to autoformat all QL.

- docs/language/learn-ql/go/ast-class-reference.rst
- ql/src/semmle/go/Expr.qll
To avoid a recursive definition, need to replace ArrayTypeExpr with@arraytypeexpr and so on in isTypeExprBottomUp(Expr e).
> Make `ArrayTypeExpr` and so on extend `TypeExpr`

- ql/src/semmle/go/AST.qll
- ql/src/semmle/go/Comments.qll
- ql/src/semmle/go/Decls.qll
- ql/src/semmle/go/Expr.qll
- ql/src/semmle/go/Files.qll
- ql/src/semmle/go/GoMod.qll
- ql/src/semmle/go/PrintAst.ql
- ql/src/semmle/go/PrintAst.qll
- ql/src/semmle/go/Stmt.qll
- ql/test/library-tests/semmle/go/PrintAst/PrintAst.expected
- ql/test/library-tests/semmle/go/PrintAst/PrintAst.ql
- ql/test/library-tests/semmle/go/PrintAst/input.go
Known shortcomings:
* Uses getAQlClass rather than tagging AST nodes with a canonical class, as the C++ version of the same query does
* Types and go.mod lines are not printed informatively (typically we just get a short description of the node kind, e.g. 'function type')
* Children are always named for their child indices; we should give informative names to the edges where an accessor is declared (e.g. IfStmt names its children 'init', 'cond', 'if', 'else')
Reviewers: do you want to see those features in v1, or do you want a barebones version in then add those afterwards?
> Add barebones PrintAST for Go

- ql/src/semmle/go/AST.qll
- ql/src/semmle/go/Decls.qll
- ql/src/semmle/go/Expr.qll
* Centralise use of raw types and database predicates in FieldParent and FieldBase classes
* Deduplicate type predicates common to all fields
* Deduplicate predicates common to function parameters and results
> Clean up @field and @fieldparent usage

- ql/src/semmle/go/PrintAst.qll
It's bland, but we try to maintain a 100% documentation coverage for our public library elements.
> Add qldoc for three public predicates in `PrintAst.qll`.

- change-notes/2020-06-19-call-graph.md
- ql/src/semmle/go/dataflow/internal/DataFlowDispatch.qll
- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
- ql/test/library-tests/semmle/go/dataflow/CallGraph/getACallee.expected
- ql/test/library-tests/semmle/go/dataflow/CallGraph/test.go
When faced with a call `x.m()` where the type of `x` is some interface `I`, `getACallee()` does the conservative thing and resolves the call to all overriding definitions of `m`.
For the data-flow analysis, we try a bit harder: the `viableCallee` predicate checks whether it can by local reasoning determine a concrete (non-interface) type for `x`, or perhaps a set of such types, and then resolves `m` on those.
This PR adds an orthogonal refinement: even if we can't determine a concrete type for `x`, we can still require that the overriding definition of `m` we select must belong to a type that implements `I`. This isn't a trivial condition, since `I` might inherit `m` from another interface `J`, and this way we might be able to exclude some definitions of `m` in types that implement `J` …
> Refine potential targets for method call through interface

- ql/src/semmle/go/Concepts.qll
- ql/src/semmle/go/frameworks/Stdlib.qll
I noticed that we sometimes use them unqualified and sometimes use them qualified so I thought I'd standardize them without the qualifier.
> Unqualify uses of FunctionInput and FunctionOutput

- ql/src/semmle/go/Stmt.qll
- ql/src/semmle/go/controlflow/ControlFlowGraphImpl.qll
- ql/test/library-tests/semmle/go/controlflow/ControlFlowGraph/ControlFlowNode_getASuccessor.expected
- ql/test/library-tests/semmle/go/controlflow/ControlFlowGraph/tst.go
Previously we thought it possible to get from top to bottom of a block like `switch { case f(): ... }`, when in fact this is only possible if there are no case blocks to execute.
I also add tests for two possible corner cases of a switch without a test-expression: a completely empty switch (the 'true' is indeed the last node) and switch with an empty default block (a single 'skip' is generated for the default block and the 'true' is not the last node)
> Remove spurious control-flow edge around switch block without a test

- change-notes/2020-06-24-open-redirect.md
- ql/src/semmle/go/security/OpenUrlRedirect.qll
- ql/test/query-tests/Security/CWE-601/OpenUrlRedirect/OpenUrlRedirect.expected
- ql/test/query-tests/Security/CWE-601/OpenUrlRedirect/stdlib.go
This allows us to flag CVE-2018-15798, as confirmed by the [evaluation](https://github.com/max-schaefer/dist-compare-reports/blob/master/go/cve-2018-15798/report.md) (internal link).
In theory, there is a potential for imprecise flow into the `Host` field and then out of `Path` (or similar). The evaluation suggests that this doesn't happen in practice, and a run across all of LGTM.com showed only a handful of new results, all of them reasonable.
> Teach `OpenUrlRedirect` to propagate out of `URL.Path` and a few other fields.

- change-notes/2020-06-26-taint-through-range.md
- ql/src/semmle/go/controlflow/IR.qll
- ql/src/semmle/go/dataflow/internal/TaintTrackingUtil.qll
- ql/test/experimental/CWE-327/UnsafeTLS.expected
- ql/test/experimental/CWE-327/UnsafeTLS.go
- ql/test/library-tests/semmle/go/dataflow/FlowSteps/LocalFlowStep.expected
- ql/test/library-tests/semmle/go/dataflow/FlowSteps/LocalTaintStep.expected
- ql/test/library-tests/semmle/go/dataflow/FlowSteps/main.go
I apparently just plain forgot about that when writing the original taint-tracking library. :facepalm: 
An [evaluation](https://github.com/max-schaefer/dist-compare-reports/blob/master/go/taint-through-range/report.md) (internal link) shows OK performance. I suspect that the two outliers at the bottom would go away with rerunning, but unfortunately don't have enough workers available to confirm. (**EDIT**: I have now confirmed that rerunning removes the outliers, so performance is not affected by this PR.)
The new results are a slightly mixed bag: the `go/allocation-size-overflow` ones are fine; the `go/request-forgery` ones are technically correct but look intentional; and the `go/reflected-xss` one is a false positive. However, the dubious results aren't the fault of this PR, they are …
> Propagate taint through `range` statements

- extractor/gomodextractor.go
- ql/test/extractor-tests/go-mod-comments/commentGroups.expected
- ql/test/extractor-tests/go-mod-comments/commentGroups.ql
- ql/test/extractor-tests/go-mod-comments/comments.expected
- ql/test/extractor-tests/go-mod-comments/comments.ql
- ql/test/extractor-tests/go-mod-comments/go.mod
The comment group is now omitted entirely if empty, and otherwise delimits the range of the comments ascribed to this group.
Pre-emptive reviewer response: yes, really, Go's `math` package only provides `Min` and `Max` for float types, so you either have to cast back and forth, take a dependency such as `github.com/pkg/math` or write your own `IntMin` and `IntMax`.
> Extractor: give the go.mod comment groups a source location

- extractor/cli/go-autobuilder/go-autobuilder.go
Reverts github/codeql-go#165
As discussed, this needs some more thought.
> Revert "autobuilder: Add support for GITHUB_REPOSITORY environment variable"

- ql/src/semmle/go/dataflow/FunctionInputsAndOutputs.qll
This is for consistency with TFunctionInput, which already does this
> Make receiver a separate case in TFunctionOutput

- change-notes/2020-06-12-more-dependency-extraction.md
- extractor/cli/go-autobuilder/go-autobuilder.go
- extractor/extractor.go
- extractor/util/util.go
A [dist-compare](https://git.semmle.com/sauyon/dist-compare-reports/tree/0460ebb817c6ecedbc9f2fcf2495c70e19354564) shows 60 new results on kubernetes due to the new way that files are picked up.
The results that I looked at look like false positives, but are reasonable, so I'm going to open issues for them and not worry about them for this PR.
Also, evaluation has slowed significantly for both `cadence` and `kubernetes`.
Matt established that the OS X issues I've been having are an issue with the tracer, and he's working on that now.
> Extract more dependency ASTs

- ql/test/experimental/CWE-322/vendor/golang.org/x/crypto/ssh/stub.go
- ql/test/library-tests/semmle/go/Types/SignatureType_getNumResult.expected
- ql/test/library-tests/semmle/go/Types/depth.go
Found while testing the upcoming support for consistency queries in `codelq test run` :tada:
The second commit is due to a bug in depstubber (https://github.com/github/depstubber/issues/5), which I have worked around manually for now.
> Fix frontend errors

- ql/src/semmle/go/dataflow/internal/DataFlowDispatch.qll
- ql/src/semmle/go/dataflow/internal/DataFlowImpl.qll
- ql/src/semmle/go/dataflow/internal/DataFlowImplCommon.qll
- ql/src/semmle/go/dataflow/internal/DataFlowPrivate.qll
It's been a busy week in data flow, apparently. [Evaluation](https://github.com/max-schaefer/dist-compare-reports/blob/master/go/update-data-flow/report.md) (internal link) is uneventful; note that I reran a few performance outliers, which turned out not to be reproducible and hence were most likely wobbles.
> Update shared data-flow libraries

- ql/src/experimental/CWE-322/InsecureHostKeyCallback.ql
We'll add it back when we take it out of experimental status.
> Remove `@precision` from experimental query.

- ql/src/semmle/go/Scopes.qll
- ql/src/semmle/go/controlflow/ControlFlowGraph.qll
- ql/src/semmle/go/controlflow/ControlFlowGraphImpl.qll
- ql/src/semmle/go/frameworks/Stdlib.qll
- ql/src/semmle/go/frameworks/Testing.qll
- ql/test/library-tests/semmle/go/controlflow/ControlFlowGraph/ControlFlowNode_getASuccessor.expected
- ql/test/library-tests/semmle/go/controlflow/ControlFlowGraph/NoretFunctions.expected
- ql/test/library-tests/semmle/go/controlflow/ControlFlowGraph/NoretFunctions.ql
- ql/test/library-tests/semmle/go/controlflow/ControlFlowGraph/noretfunctions.go
We also use this to note that user-defined functions can only return normally if their CFG normal exit node is reachable, and annotate some well-known functions as noreturn.
For example, this will by fiat declare os.Exit noreturn (never returns normally), and will also notice that a user function `func myExit() { os.Exit(1) }` is also noreturn, because it doesn't have any control-flow edges that reach the normal return node.
Note that the test diff shows some expected changes to other functions' CFGs, which happens because `stmts.go` / `test5` and a few other test functions cannot return. 
There are also a couple of apparently-unrelated changes, but these turn out to be because most of `test8` is in fact unreachable due to unconditionally calling `test5` early on. A partial, unconnected …
> Switch from using mustPanic to mayReturnNormally to construct a call-expression's CFG

- ql/src/semmle/go/frameworks/Stdlib.qll
Make sure that the taint-tracking class for the `String()` method checks that the result type is a string.
> taint-tracking: String() must return a string type

- change-notes/2020-07-07-missing-error-check.md
- ql/src/InconsistentCode/MissingErrorCheck.go
- ql/src/InconsistentCode/MissingErrorCheck.qhelp
- ql/src/InconsistentCode/MissingErrorCheck.ql
- ql/src/InconsistentCode/MissingErrorCheckGood.go
- ql/test/query-tests/InconsistentCode/MissingErrorCheck/MissingErrorCheck.expected
- ql/test/query-tests/InconsistentCode/MissingErrorCheck/MissingErrorCheck.qlref
- ql/test/query-tests/InconsistentCode/MissingErrorCheck/tests.go
Note there was some review of the draft at https://github.com/github/codeql-go/pull/228; recreated because I had used a stupid branch name by mistake.
This is no longer a draft and is ready for review.
A full evaluation is at https://lgtm.com/query/9012966599211609480/ -- after reviewing the 50 top projects ordered by nhits all matches appear correct assuming the callee library function may really return a nil pointer.
> Add query searching for missing error checks on functions that return a (pointer, error) pair

- extractor/gomodextractor.go
- ql/test/extractor-tests/go-mod-comments/commentGroups.expected
- ql/test/extractor-tests/go-mod-comments/commentGroups.ql
The schema requires that (parent, index) is a key.
> Extractor: assign unique indices to comment-groups in go.mod files

- ql/src/ideContextual.qll
- ql/src/localDefinitions.ql
- ql/src/localReferences.ql
- ql/src/printAst.ql
This is similar to the cpp query for printing the AST in the context of VS Code.
This PR also includes a small refactoring to extract the `getEncodedFile` predicate to a new `qll` file.
Fixes #260.
> Add the printAst contextual query

- ql/src/semmle/go/AST.qll
- ql/src/semmle/go/Expr.qll
- ql/src/semmle/go/PrintAst.qll
- ql/test/library-tests/semmle/go/PrintAst/PrintAst.expected
This adds support for generally overriding the default AstNode child ordering, and uses it to sort parameter and result declarations in the context of a FuncTypeExpr in left-to-right textual order.
> PrintAst: order parameter and result declarations

- ql/src/printAst.ql
- ql/src/semmle/go/PrintAst.ql
- ql/src/semmle/go/PrintAst.qll
- ql/test/library-tests/semmle/go/PrintAst/PrintAst.expected
- ql/test/library-tests/semmle/go/PrintAst/PrintAstExcludeComments.expected
- ql/test/library-tests/semmle/go/PrintAst/PrintAstExcludeComments.ql
- ql/test/library-tests/semmle/go/PrintAst/PrintAstNestedFunction.expected
- ql/test/library-tests/semmle/go/PrintAst/PrintAstNestedFunction.ql
- ql/test/library-tests/semmle/go/PrintAst/PrintAstRestrictFile.expected
- ql/test/library-tests/semmle/go/PrintAst/PrintAstRestrictFile.ql
- ql/test/library-tests/semmle/go/PrintAst/PrintAstRestrictFunction.expected
- ql/test/library-tests/semmle/go/PrintAst/PrintAstRestrictFunction.ql
- ql/test/library-tests/semmle/go/PrintAst/go.mod
- ql/test/library-tests/semmle/go/PrintAst/other.go
* Exclude function definitions, not just their children, when excluded by configuration
* Allow excluding files
* Allow excluding comments
* Sort root files
* Tests for all of the above
> PrintAst: improve support for restricting subsets of the AST to print

- ql/src/semmle/go/PrintAst.qll
- ql/test/library-tests/semmle/go/PrintAst/PrintAst.expected
- ql/test/library-tests/semmle/go/PrintAst/PrintAstExcludeComments.expected
- ql/test/library-tests/semmle/go/PrintAst/PrintAstNestedFunction.expected
- ql/test/library-tests/semmle/go/PrintAst/PrintAstRestrictFile.expected
- ql/test/library-tests/semmle/go/PrintAst/PrintAstRestrictFunction.expected
As requested in https://github.com/github/codeql-go/issues/265
> PrintAst: Label File nodes' package-name children, and ensure that child comes before all declarations

- ql/src/codeql-suites/go-lgtm-full.qls
This PR extends the `lgtm-full.qls` suite to also include the non-alert queries that LGTM runs. This is important when we switch to using CodeQL instead of ODASA in LGTM.
@max-schaefer
> CodeQL: complete LGTM suites

- Makefile
This should have been looking for \.go$, but I forgot to escape the dollar sign in a Makefile
> Escape go-fmt file filter

- ql/src/semmle/go/dataflow/SSA.qll
Initial evaluation was positive, but with a few outliers in both directions:
Project | before | after | after/before
--|--|--|-
gobot_9a9d580de37056c636751930c9b33c03c294d3a9 | 135 | 59 | 0.437037
hydra_7f50b944ea7a0bc02f37a08c860670bd33453986 | 86 | 42 | 0.488372
gobot_9b97c70ca6bed3ef922d8e43a01e4524e956a04a | 98 | 60 | 0.612245
sourcegraph_bde46f4ae891ca5bccaab042cab8fa72f6c2b165 | 237 | 175 | 0.738397
hydra_9b5bbd48a72096930af08402c5e07fce7dd770f3 | 50 | 42 | 0.84
sourcegraph_2555ef0e46d4b0c457cb1894d63773af48821388 | 214 | 186 | 0.869159
lyft-go-samples | 21 | 20 | 0.952381
pam-ussh | 21 | 20 | 0.952381
image_a3d69a4a89244803d2f5350aca6dd0fcbe444551 | 44 | 42 | 0.954545
assume-role-cli | 23 | 22 | 0.956522
carbonserver | 23 | 22 | 0.956522
lyft-go-sdk | 23 | 22 | 0.956522 …
> Speed up `unresolvedReference`.

- upgrades/ee5c327face2866a7b3b12dcce5c291be52ebf52/upgrade_comment_groups.ql
I noticed that this script was taking a very long time to upgrade a database of `cockroach` downloaded from LGTM.com, probably due to a bad join ordering. This seems to fix it.
> Improve performance of upgrade script

- README.md
It turns out there are only two references to master that involve this repository:
* A link in our readme, which I've changed
* A link in our change notes, which I've left unchanged because I'm not sure if we should edit those.
> Fix one use of master in README

- change-notes/2020-08-07-negative-length-check.md
- ql/src/RedundantCode/NegativeLengthCheck.qhelp
- ql/src/RedundantCode/NegativeLengthCheck.ql
- ql/test/query-tests/RedundantCode/NegativeLengthCheck/NegativeLengthCheck.expected
- ql/test/query-tests/RedundantCode/NegativeLengthCheck/main.go
Like return values from len and cap, unsigned integers are never negative.
This allows us to catch [CVE-2018-18206](https://www.whitesourcesoftware.com/vulnerability-database/CVE-2018-18206).
> Extend negativeLengthCheck query to unsigned integers

- ql/src/ideContextual.qll
- ql/src/semmle/go/security/InsecureFeatureFlag.qll
These are the only two public symbols without docs in the release.
> Document undocumented public symbols

- ql/src/go.qll
Thanks to  @RasmusWL for pointing out this oversight.
> Import Gin framework by default

- .github/workflows/codeqltest.yml
This reverts commit 8aaa7c89252ae7a4aca91b03ac1a3e703eb2b1de.
The bug it was working around (if it ever did) has been fixed.
> Revert "Downgrade to checkout@v1 to work around https://github.com/actions/checkout/issues/237"

- ql/src/Security/CWE-681/IncorrectIntegerConversion.qhelp
It seems qhelp doesn't like `<code>` inside `<a>`.
> Fix qhelp for incorrect integer-conversion query.

- ql/src/Security/CWE-079/ReflectedXssGood.go
- ql/test/query-tests/Security/CWE-079/ReflectedXssGood.go
Previously, the "good" example still had the "BAD: " comment in it which was confusing.
This change updates the good example to have a "GOOD: " comment instead.
> Update bad / good message for CWE 079

- ql/src/semmle/go/StringOps.qll
- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
This is a regression relative to 1.24, hence a hotfix.
> Prevent misoptimisation in `StringOps`.

- change-notes/2020-08-19-gin-model.md
This was originally put in too early because the Gin framework was
accidentally not added to the default includes.
This reverts commit 41e98d6afc0d4ef7be25c8545231eb6589c8bb58.
> Add change note for Gin framework

- extractor/cli/go-autobuilder/go-autobuilder.go
- extractor/util/util.go
This is #310 with additions:
* Always check vendor/ is usable if we're about to use it
* Only use `-mod` when go.mod exists
* Factor the paths using `checkVendor` (optional, could drop)
Locally verified this fixes a further 24 projects; proceeding to build a dist and check on all projects.
> Autobuilder: always check the vendor directory works and if go.mod exists

- ql/src/Security/CWE-190/AllocationSizeOverflow.ql
- ql/src/semmle/go/security/AllocationSizeOverflowCustomizations.qll
- ql/test/query-tests/Security/CWE-190/AllocationSizeOverflow.expected
- ql/test/query-tests/Security/CWE-190/tst3.go
This fixes one source of FPs. In principle it's easy because we can just add an extra sanitizer guard. In practice this path query has three important nodes rather than the standard two (source and sink), so the second node is made the sink and its characteristic predicate includes the fact that taint can flow to the third node. The new sanitizer guard can only occur between the second and third node, whereas all the old sanitizers and sanitizer guards occur between the first and second, so they fitted well into this scheme. Thus a little bit of the logic of the dataflow library has to be duplicated to make sure that the third node isn't guarded by the new sanitizer guard.
I'm not sure if it's better to put this check at the definition of the sink or in the query. If you look …
> Add new sanitizer guard to Allocation size overflow query

- ql/test/query-tests/Security/CWE-190/tst3.go
Introduced in https://github.com/github/codeql-go/pull/309, which was based on a version of `master` that didn't have the consistency checks yet.
> Fix frontend errors in test.

- extractor/cli/go-autobuilder/go-autobuilder.go
This works fine in testing, so long as the DB is outside the source tree:
```
chris@orchard:/tmp/x$ SEMMLE_REPO_URL=http://chriskindrepos.org/myorg/myproj codeql database create --language=go ../y
Initializing database at /private/tmp/y.
Running command [/Users/chris/codeql-home/codeql-go/build/codeql-extractor-go/tools/autobuild.sh] in /private/tmp/x.
[2020-08-13 12:57:50] [build-err] 2020/08/13 12:57:50 Autobuilder was built with go1.14.4, environment has go1.14.4
[2020-08-13 12:57:50] [build-err] 2020/08/13 12:57:50 LGTM_SRC is /tmp/x
[2020-08-13 12:57:50] [build-err] 2020/08/13 12:57:50 Import path is 'chriskindrepos.org/myorg/myproj'
[2020-08-13 12:57:50] [build-err] 2020/08/13 12:57:50 Temporary directory is /tmp/x/scratch382870414.
[2020-08-13 12:57:50] [build-err] 2020/08/13 …
```
> Restore repo layout post-autobuild

- extractor/cli/go-autobuilder/go-autobuilder.go
This reverts commit ccfccb4828cf5b2b90035ab2b22d2098418c43ea, effectively reinstating #165. This should be safe now that https://github.com/github/codeql-go/pull/287 has been merged.
> Revert "Revert "autobuilder: Add support for GITHUB_REPOSITORY environment variable""

- change-notes/2020-09-10-xss-false-positives.md
- ql/src/semmle/go/security/ReflectedXssCustomizations.qll
- ql/test/query-tests/Security/CWE-079/ReflectedXss.expected
- ql/test/query-tests/Security/CWE-079/ReflectedXss.go
Previously we only detected these if the marshalling directly fed the request body within the same function; now it's a general sanitiser for the purposes of XSS.
> Reflected XSS query: exclude more uses of encoding/json.Marshal

- ql/src/semmle/go/dataflow/FunctionInputsAndOutputs.qll
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionInput_getEntryNode.expected
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionInput_getExitNode.expected
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionModelStep.expected
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionOutput_getEntryNode.expected
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionOutput_getExitNode.expected
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionOutput_isResult.expected
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionOutput_isResult_int.expected
- ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/tst2.go
Currently, the entry node is required to be a post-update SSA node, so we get an entry node for the result of `NewEncoder` in this snippet:
```go
enc := json.NewEncoder(w)
enc.Encode(data)
```
But not in this one:
```go
json.NewEncoder(w).Encode(data)
```
This is unfortunate, since in this case it prevents us from stitching together the models for `Encode` (first argument -> receiver) and `NewEncoder` (result -> first argument).
This PR proposes to fix this by taking the entry node to be the result itself if it isn't assigned to an SSA variable. (We still do want it to be the SSA variable if there is one, since otherwise we'd lose flow in the first example.)
It feels like there should be a more principled solution, but for now I think this fixes our immediate problem.
For ease of …
> Ensure `FunctionInput`s corresponding to results have an entry node

- ql/src/semmle/go/frameworks/stdlib/NetHttp.qll
- ql/test/library-tests/semmle/go/frameworks/StdlibTaintFlow/NetHttp.go
noting that if the URL is tainted then the response should be considered tainted also. See https://github.com/github/securitylab/discussions/183
> Add model for net/http.NewRequest

- change-notes/2020-09-22-suspicious-character-in-regexp.md
- ql/src/Security/CWE-020/SuspiciousCharacterInRegexp.go
- ql/src/Security/CWE-020/SuspiciousCharacterInRegexp.qhelp
- ql/src/Security/CWE-020/SuspiciousCharacterInRegexp.ql
- ql/src/Security/CWE-020/SuspiciousCharacterInRegexpGood.go
- ql/test/query-tests/Security/CWE-020/SuspiciousCharacterInRegexp/SuspiciousCharacterInRegexp.expected
- ql/test/query-tests/Security/CWE-020/SuspiciousCharacterInRegexp/SuspiciousCharacterInRegexp.qlref
- ql/test/query-tests/Security/CWE-020/SuspiciousCharacterInRegexp/test.go
Inspired by js/useless-regexp-character-escape, but much much simpler because the Go source code parser forbids unrecognised escapes and its regex engine refuses to compile \\x where x is not a character class or other special token (e.g. start-of-word). The only potentially troublesome sequences are `\a` (confused for `\\A` or Vim's `\\a` perhaps) and `\b` (probably confused for `\\b`, start-of-word anchor).
Evaluated on lgtm.com, found two results, one probable and one true positive, so clearly this is a much rarer mistake in Go than in JS, but I figure it doesn't hurt to have the query.
> Add query spotting probably-bad escapes in regular expressions.

- ql/src/codeql-suites/go-lgtm-full.qls
The `go-lgtm-full.qls` should match the query suite as run by LGTM. The `Metrics/FLinesOfComment.ql ` query was missing.
> LGTM: add Metrics/FLinesOfComment.ql to go-lgtm-full.qls

- extractor/extractor.go
These changes are mostly changes that were for Kubernetes.
- Package directory as a wanted root
This makes the extractor actually extract vendor packages when they're explicitly passed to a build command; before the wanted root would be the mod directory, and so the all the files would because the relative path to the root includes `vendor`. I'm not 100% sure we should do this, but that was my intention when I made the original changes, so I've changed this.
- Enable Go modules while determining module directory
This force enables modules while running `go list -f {{.Module}} ...` so that even if `GO111MODULE=off` is set manually, we can still detect module directory. This is done by Kubernetes, and the change increases the coverage of the database significantly.
- Improve extractor …
> Improve extractor logging and a minor readability fix

- .github/workflows/codeqltest.yml
- Makefile
- scripts/qhelp-to-markdown.sh
This tests that qhelp builds to markdown, and uploads an artefact containing the built help. I punted on determining which qhelp files you consider changed in a local checkout / push build / PR build since the total build time is about 10 seconds and the artefact is 40KB.
> Add Action to build and upload qhelp

- ql/src/Security/CWE-020/SuspiciousCharacterInRegexp.go
- ql/src/Security/CWE-020/SuspiciousCharacterInRegexpGood.go
These were inherited from the JS version of the example, which concerns HTML.
> Improve variable names in example code

- extractor/cli/go-autobuilder/go-autobuilder.go
Otherwise on systems where /tmp is a symlink (e.g. default OSX setup), GOPATH does not match the current working directory after os.Chdir'ing to that directory (os.Chdir resolves symlinks, unlike a shell's 'cd' command), which causes `dep` to fail complaining that it is being run from outside GOPATH.
> Autobuilder: Use fully resolved path for GOPATH

- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
This makes it easier to refine FunctionNode without having to define abstract members.
> Refactor DataFlow::FunctionNode as a concrete class

- change-notes/2020-10-01-stack-trace-exposure.md
- ql/src/Security/CWE-209/StackTraceExposure.go
- ql/src/Security/CWE-209/StackTraceExposure.qhelp
- ql/src/Security/CWE-209/StackTraceExposure.ql
- ql/test/query-tests/Security/CWE-209/StackTraceExposure.expected
- ql/test/query-tests/Security/CWE-209/StackTraceExposure.qlref
- ql/test/query-tests/Security/CWE-209/test.go
This is a port of `java/stack-trace-exposure`, and does the same job: warn that a stack dump is written to an HTTP response.
LGTM evaluation reveals 13 true positives and 2 false positives that are too difficult to analyse: one in which an HTTP handler is only registered in the first place (via an anonymous function assigned to a temporary variable) contingent on a debug-mode flag, and one in which a custom `needsAdmin` pass-through filter is used to avoid exposing traces to non-root users.
The true positives are true in the sense that they really do expose the stack to a remote party, but don't look like accidents, as they often have their own dedicated route, called something like `host.com/debug/goroutines`. I would argue this is a useful query anyhow, since (a) that serves to warn …
> Add stack-trace exposure query

- Makefile
Previously, invoking `make autoformat` would run a command of this form:
```sh
... | grep \\.go$ | ...
```
Note that the `$` is not escaped. This probably wasn't intended, even though it happens to work anyway, since the shell doesn't try to expand lone `$`s.
More problematically, invoking `make check-formatting` would run a command of this form:
```sh
... | grep \\.go| ...
```
Note that the `$` is gone, so it matches `.go` anywhere in the file name. In particular, it matches `ql/test/library-tests/semmle/go/frameworks/Protobuf/vendor/google.golang.org/protobuf/LICENSE`, which I think is responsible for the somewhat mysterious "expected 'package', found Copyright" errors we occasionally saw in CI. (Though the recently added `grep -v vendor` also fixed that.)
This PR fixes both targets to …
> Fix escaping in Makefile targets.

- Makefile
- change-notes/2020-10-14-allocation-overflow-accuracy.md
- ql/src/go.qll
- ql/src/semmle/go/dataflow/DataFlow2.qll
- ql/src/semmle/go/dataflow/TaintTracking2.qll
- ql/src/semmle/go/dataflow/internal/DataFlowImpl2.qll
- ql/src/semmle/go/dataflow/internal/tainttracking2/TaintTrackingImpl.qll
- ql/src/semmle/go/dataflow/internal/tainttracking2/TaintTrackingParameter.qll
- ql/src/semmle/go/security/AllocationSizeOverflow.qll
- ql/src/semmle/go/security/AllocationSizeOverflowCustomizations.qll
- ql/test/query-tests/Security/CWE-190/array_vs_contents.go
This is achieved by splitting the query into two pieces: (1) trace flow from indefinitely large object creation to len(...) calls, then (2) considering those particular len(...) calls as taint propagators, trace taint from the same sources all the way to an allocation call. This is more accurate than the previous solution, which considered any len(...) call to propagate taint, potentially confusing an array that stored a large value in one of its cells for an array which is itself of large size.
> Improve accuracy of allocation-size-overflow by excluding len(...) calls that never see a large operand

- Makefile
- change-notes/2020-06-11-build-tracing.md
- codeql-tools/autobuild.cmd
- codeql-tools/autobuild.sh
- codeql-tools/linux64/compiler-tracing.spec
- codeql-tools/osx64/compiler-tracing.spec
- codeql-tools/win64/compiler-tracing.spec
- extractor/autobuilder/autobuilder.go
- extractor/cli/go-autobuilder/go-autobuilder.go
- extractor/cli/go-build-runner/go-build-runner.go
- extractor/cli/go-extractor/go-extractor.go
- extractor/extractor.go
- extractor/util/util.go
I'd forgotten quite how long dist-compares take, especially since the kubernetes dependencies aren't being dropped (because codeql doesn't support the `lgtm.yml` files).
I've put this up for review anyway, since that seemed like a good idea.
> Build tracing

- extractor/cli/go-autobuilder/go-autobuilder.go
This can happen under tracing, perhaps because of https://github.com/github/codeql-tracer/issues/29
> Autobuilder: fall back when os.Executable fails

- ql/src/semmle/go/controlflow/ControlFlowGraphImpl.qll
- ql/test/library-tests/semmle/go/controlflow/ControlFlowGraph/ControlFlowNode_getASuccessor.expected
- ql/test/library-tests/semmle/go/controlflow/ControlFlowGraph/main.go
- ql/test/library-tests/semmle/go/controlflow/ControlFlowGraph/stmts2.go
- ql/test/query-tests/RedundantCode/DeadStoreOfLocal/DeadStoreOfLocal.expected
- ql/test/query-tests/RedundantCode/DeadStoreOfLocal/testdata.go
For example, "x, _ := a, b" would produce an incorrect CSV that branched to the next statement after evaluating "b", skipping the assignment to 'x'. We already had test coverage for function returns, so I'm reasonably confident this only affects parallel assigns, not destructuring ones like "x, y := f()".
> CFG: fix lastNode relating to assignments with underscores on the LHS

- ql/src/ideContextual.qll
- ql/src/localDefinitions.ql
- ql/src/localReferences.ql
- ql/src/printAst.ql
While also making it work with paths for databases created on Windows.
This matches the changes in https://github.com/github/codeql/pull/4643
> Replace getEncodedFile with getFileBySourceArchiveName predicate

- extractor/cli/go-autobuilder/go-autobuilder.go
- extractor/util/util.go
Ran into some issues when testing a few projects where builds were unrelated to Go / exited 0 despite failing, so I wrote this quick change.
> Check dependencies before skipping dependency installation

- ql/src/semmle/go/dataflow/Properties.qll
- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
- ql/test/library-tests/semmle/go/dataflow/GuardingFunctions/test.go
- ql/test/library-tests/semmle/go/dataflow/GuardingFunctions/test.ql
We already made some effort to recognise guard functions like
```go
func isGood(validateMe string) bool {
if countProblems(validateMe) == 0 { // we have a DataFlow::BarrierGuard model of countProblems(...) == 0
return true
} else {
return false
}
}
```
This PR adds a variety of other possible forms for such functions:
```go
return countProblems(validateMe) == 0
return countProblems(validateMe) && somethingElse()
return !(countProblems(validateMe) == 0)
return isGood2(validateMe) // which itself calls countProblems
```
See the test added by this PR for a complete list of the forms now recognised.
We also add support for functions that indicate something is sanitized by returning nil, typically a `nil` `error` value.
> Recognise many more guarding functions

- change-notes/2020-11-12-zipslip-sanitizers.md
- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
- ql/src/semmle/go/security/ZipSlipCustomizations.qll
- ql/test/query-tests/Security/CWE-022/ZipSlip.expected
- ql/test/query-tests/Security/CWE-022/ZipSlipGood2.go
- ql/test/query-tests/Security/CWE-022/tarslip.go
Previously we considered certain fields of `tar` or `zip` file headers to be sources, but this meant subsequent references to the same field were not considered sanitized. For example, at least some real-world projects used a pattern like `if isIllegalPathTraversal(hdr.Name) { return nil; } ... /* other code using hdr.Name */`. By associating a source with the field-read `.Name` rather than the header itself, we were unable to see that the subsequent read was guarded by the sanitizer function, except in some cases where `SsaWithFields` associated the two closely enough.
Relatedly, it is common to use some intermediary taint-propagating function, as in `clean(s string) { if strings.HasPrefix("..", filepath.Clean(filepath.Join(target, s))) ...`, in the implementation of a sanitizer. We now …
> ZipSlip: redefine sources closer to their origin, and make sanitizers more generous

- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
This enables recognising more guarding functions that return nil/non-nil conditional on a barrier guard.
> Note that `fmt.Errorf` returns non-nil

- CONTRIBUTING.md
This should help new contributors get started a little quicker.
> Docs: Add building and testing to contributing guide

- ql/src/Security/CWE-078/CommandInjection.ql
- ql/src/semmle/go/Concepts.qll
- ql/src/semmle/go/frameworks/SystemCommandExecutors.qll
- ql/src/semmle/go/security/CommandInjection.qll
- ql/src/semmle/go/security/CommandInjectionCustomizations.qll
- ql/test/query-tests/Security/CWE-078/CommandInjection.expected
- ql/test/query-tests/Security/CWE-078/GitSubcommands.go
- ql/test/query-tests/Security/CWE-078/SanitizingDoubleDash.go
This is because some git flags can specify arbitrary commands to execute, but its positional arguments cannot, and "--" like in many commands instructs git to consume no further flags.
> Add 'git' as a possible command-interpreter, unless arguments are sanitized using "--"

- ql/src/Security/CWE-322/InsecureHostKeyCallback.ql
- ql/src/Security/CWE-352/ConstantOauth2State.ql
- ql/src/semmle/go/frameworks/Beego.qll
- ql/src/semmle/go/frameworks/BeegoOrm.qll
- ql/src/semmle/go/frameworks/Chi.qll
- ql/src/semmle/go/frameworks/Echo.qll
- ql/src/semmle/go/frameworks/Email.qll
- ql/src/semmle/go/frameworks/Encoding.qll
- ql/src/semmle/go/frameworks/EvanphxJsonPatch.qll
- ql/src/semmle/go/frameworks/Gin.qll
- ql/src/semmle/go/frameworks/GoRestfulHttp.qll
- ql/src/semmle/go/frameworks/K8sIoApiCoreV1.qll
- ql/src/semmle/go/frameworks/K8sIoApimachineryPkgRuntime.qll
- ql/src/semmle/go/frameworks/K8sIoClientGo.qll
- ql/src/semmle/go/frameworks/Logrus.qll
- ql/src/semmle/go/frameworks/Mux.qll
- ql/src/semmle/go/frameworks/NoSQL.qll
- ql/src/semmle/go/frameworks/Protobuf.qll
- ql/src/semmle/go/frameworks/Revel.qll
- ql/src/semmle/go/frameworks/SQL.qll
- ql/src/semmle/go/frameworks/Spew.qll
- ql/src/semmle/go/frameworks/SystemCommandExecutors.qll
- ql/src/semmle/go/frameworks/Testing.qll
- ql/src/semmle/go/frameworks/WebSocket.qll
- ql/src/semmle/go/frameworks/XNetHtml.qll
- ql/src/semmle/go/frameworks/XPath.qll
- ql/src/semmle/go/frameworks/stdlib/Context.qll
This has the advantage that it deals with versioning. For example,
`package("a.io", "b")` matches "a.io/v2/b"
as well as "a.io/b".
At the same time I have created `packagePath()` predicates where they
seemed useful and tried to standardise them a bit.
> Use `package()` for package paths not in the standard library

- change-notes/2021-01-21-default-sanitizer-guard.md
- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
- ql/src/semmle/go/dataflow/internal/TaintTrackingUtil.qll
- ql/src/semmle/go/dataflow/internal/tainttracking1/TaintTrackingImpl.qll
- ql/src/semmle/go/dataflow/internal/tainttracking2/TaintTrackingImpl.qll
- ql/src/semmle/go/security/Xss.qll
Adds the ability to create a taint sanitizer guard that applies in all configurations. (This is already possible for taint sanitizers.)
Also takes EqualityTestGuard from `Xss.qll` and makes it a default taint sanitizer guard. The thinking is that for most configurations, being tainted means being user controlled, and comparing a value to a constant means that it has been checked and found to be an expected value.
> Make EqualityTestGuard a default taint sanitizer guard

- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
The problem that this comment is trying to warn about is the following:
say you have two subclasses of BarrierGuard BG1 and BG2, both of which
contain some node g. Also assume that you have a configuration C which
specifies BG1 as a barrier guard, but not BG2. Because g is contained in
both classes, you will then still get the barrier guard definition from
BG2 due to the way dynamic dispatch works in QL.
> Make comment on BarrierGuard more specific

- ql/src/semmle/go/security/TaintedPathCustomizations.qll
Recent changes to Property.checkOn mean that in the code
```err == nil && <unrelated-condition>```
PathContainmentCheck matches the first condition and the whole `&&`
expression. Originally it would have only matched the first condition,
and this commit restores that behaviour. This pattern appears 3 times in
the tests, which all still pass.
> Make PathContainmentCheck more specific

- ql/src/semmle/go/frameworks/stdlib/HtmlTemplate.qll
- ql/test/library-tests/semmle/go/frameworks/StdlibTaintFlow/HtmlTemplate.go
These escape HTML and JavaScript anyhow; because they don't write to their return value they don't quite fit the form of EscapeFunction, so to be expedient I've simply removed their models entirely. Presumably the case where someone HTML-templates something and then uses it for a purpose where HTML sanitisation is insufficient is very rare anyhow.
> Remove models for html/template execution

- ql/src/semmle/go/controlflow/ControlFlowGraphImpl.qll
- ql/test/library-tests/semmle/go/controlflow/ControlFlowGraph/ControlFlowNode_getASuccessor.expected
- ql/test/library-tests/semmle/go/controlflow/ControlFlowGraph/equalitytests.go
These exist because an equality comparison of explicitly-incomparable interface values can panic, as can comparisons of arrays or structs containing them. Other type comparisons cannot panic.
> Remove panicking edges leading from an equality test where possible

- change-notes/2021-02-02-constant-comparison-sanitizer-guard.md
- ql/src/semmle/go/controlflow/ControlFlowGraph.qll
- ql/src/semmle/go/controlflow/ControlFlowGraphImpl.qll
- ql/src/semmle/go/controlflow/IR.qll
- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
- ql/src/semmle/go/dataflow/internal/TaintTrackingUtil.qll
- ql/test/library-tests/semmle/go/dataflow/ListOfConstantsSanitizerGuards/test.go
- ql/test/library-tests/semmle/go/dataflow/ListOfConstantsSanitizerGuards/test.ql
A function which contains a switch statement over one of its arguments, which only returns true (or false, or nil, or non-nil) inside case clauses with constant test expressions, now acts as a sanitizer guard for that argument.
There is a lot of scope for expanding this in future to cover more cases.
> List of constants sanitizer guards (switch statement in function only)

- change-notes/2021-02-15-logrus-updated.md
- ql/src/semmle/go/frameworks/Logrus.qll
- ql/test/library-tests/semmle/go/concepts/LoggerCall/logrus.go
Make methods which add data to entries sinks in their own right, rather
than trying to track the data flow of the entry to a later logging call.
This may cause some false positives, but only in the situation that
tainted data is added to an entry and that entry is never logged. It will
save us from false negatives when tainted data is added to an entry
which flows across a function boundary to a logging call.
> Simplify Logrus model

- change-notes/2021-02-09-html-templates.md
- change-notes/2021-02-10-cfg-equality-panic-edges.md
I haven't included change-notes for our partial support for Go 1.16 in the expectation we will add that note when it is complete.
> Add missing change notes

- ql/src/semmle/go/frameworks/Beego.qll
- ql/src/semmle/go/frameworks/GoRestfulHttp.qll
- ql/src/semmle/go/frameworks/SQL.qll
- ql/src/semmle/go/frameworks/WebSocket.qll
- ql/src/semmle/go/frameworks/XPath.qll
- ql/src/semmle/go/security/ExternalAPIs.qll
Beego moved from astaxie/beego to beego/beego on 13 Dec 2020. The
old location still works but is not being updated.
> Add new module path for beego and xmlpath

- extractor/cli/go-autobuilder/go-autobuilder.go
This fixes a bug I ran into while extracting a project that used `dep`; because go modules defaults to on now it doesn't do what we want.
> Explicitly set GO111MODULE to auto

- .github/workflows/docs-review.yml
When a PR is labelled with 'ready-for-docs-review', this workflow comments on the PR to notify the GitHub CodeQL docs team.
Runs on `pull_request_target` events so it can write comments to the PR.
Since this runs in the context of the base repo, it must not check out the PR or use untrusted data from the event payload.
Equivalent to https://github.com/github/codeql/pull/5285.
> Actions: Add workflow to request docs review

- ql/src/semmle/go/frameworks/EvanphxJsonPatch.qll
They were accidentally modeled as functions
> Model Apply methods correctly

- .github/problem-matchers/codeql-query-format.json
- .github/problem-matchers/codeql-syntax-check.json
- .github/problem-matchers/codeql-test-run.json
- .github/problem-matchers/make.json
- .github/workflows/codeqltest.yml
Copied problem-matchers from github/semmle-code, which is used for
running CI for github/codeql.
> Highlight error messages in CI

- ql/src/semmle/go/controlflow/ControlFlowGraphImpl.qll
- ql/src/semmle/go/controlflow/IR.qll
With the included fix for the bad join order, caching TControlFlowNode is an unalloyed benefit, reducing runtime by 10-20% for all the big projects and not increasing it for any:
https://github.com/github/codeql-dist-compare-reports/blob/owen-mc/cache-tcontrolflownode-2_1615845668088/README.md
> Cache TControlFlowNode

- extractor/cli/go-autobuilder/go-autobuilder.go
- extractor/extractor.go
- extractor/util/util.go
- ql/test/extractor-tests/diagnostics/Diagnostics.ql
This retains both their features:
* The new util.go one cached its result.
* The old go-autobuilder.go one worked under ODASA, where CODEQL_GO_EXTRACTOR_ROOT is unset but os.Executable is a useful substitute.
> Unify two implementations of GetExtractorPath

- change-notes/2021-03-05-dataflow-promoted-fields.md
- ql/src/semmle/go/Expr.qll
- ql/src/semmle/go/Scopes.qll
- ql/src/semmle/go/Types.qll
- ql/src/semmle/go/VariableWithFields.qll
- ql/src/semmle/go/controlflow/ControlFlowGraphImpl.qll
- ql/src/semmle/go/controlflow/IR.qll
- ql/src/semmle/go/dataflow/SSA.qll
- ql/src/semmle/go/frameworks/Revel.qll
- ql/test/library-tests/semmle/go/Types/Field_getPackage.expected
- ql/test/library-tests/semmle/go/Types/Field_hasQualifiedName2.expected
- ql/test/library-tests/semmle/go/Types/Field_hasQualifiedName3.expected
- ql/test/library-tests/semmle/go/Types/MethodTypes.expected
- ql/test/library-tests/semmle/go/Types/QualifiedNames.expected
- ql/test/library-tests/semmle/go/Types/StructFields.expected
- ql/test/library-tests/semmle/go/Types/Types.expected
- ql/test/library-tests/semmle/go/Types/cyclic.go
- ql/test/library-tests/semmle/go/Types/embedded.go
- ql/test/library-tests/semmle/go/dataflow/PromotedFields/DataFlowConfig.ql
- ql/test/library-tests/semmle/go/dataflow/PromotedFields/LocalFlowStep.expected
- ql/test/library-tests/semmle/go/dataflow/PromotedFields/LocalFlowStep.ql
- ql/test/library-tests/semmle/go/dataflow/PromotedFields/main.go
- ql/test/library-tests/semmle/go/dataflow/PromotedMethods/DataFlowConfig.ql
- ql/test/library-tests/semmle/go/dataflow/PromotedMethods/methods.go
- ql/test/query-tests/Security/CWE-022/ZipSlip.expected
We need these to understand that if we write tainted data into a promoted field `outer.Inner.field` and read from `outer.field`, where `Inner` is an embedded field of `Outer`, then we get tainted data out.
This PR assumes that embedded fields are not pointer-typed. As follow-on work we should deal with this, either by introducing an analogue of `MkImplicitDeref` for `ImplicitFieldReadInstruction`s, or by making `ImplicitFieldReadInstruction` implicitly include a deref when needed.
> Add control flow nodes for implicit fields reads when reading a promoted field

- ql/src/experimental/CWE-79/HTMLTemplateEscapingPassthrough.qhelp
- ql/src/experimental/CWE-79/HTMLTemplateEscapingPassthrough.ql
- ql/src/experimental/CWE-79/HTMLTemplateEscapingPassthroughBad.go
- ql/src/experimental/CWE-79/HTMLTemplateEscapingPassthroughGood.go
- ql/test/experimental/CWE-79/HTMLTemplateEscapingPassthrough.expected
- ql/test/experimental/CWE-79/HTMLTemplateEscapingPassthrough.go
- ql/test/experimental/CWE-79/HTMLTemplateEscapingPassthrough.qlref
This PR adds a new experimental query regarding [CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')](https://cwe.mitre.org/data/definitions/79.html), and more specifically the cases when user-values are converted to types that allow completely avoiding the escaping that normally values would undergo in the HTML template execution.
Usage of such types on user-provided values leads to XSS.
> Add CWE-79: HTML template escaping passthrough

- change-notes/2021-04-19-http-request-taint-flow.md
- ql/src/semmle/go/frameworks/stdlib/MimeMultipart.qll
- ql/src/semmle/go/frameworks/stdlib/NetHttp.qll
- ql/test/library-tests/semmle/go/frameworks/XNetHtml/ReflectedXss.expected
- ql/test/query-tests/Security/CWE-022/TaintedPath.expected
- ql/test/query-tests/Security/CWE-079/ReflectedXss.expected
- ql/test/query-tests/Security/CWE-079/ReflectedXss.go
* Don't taint error returns from http.Request methods
* Track taint across mime/multipart.Part methods
Dist-compare ~underway~ shows no changes.
> Improve net/http taint-tracking fidelity

- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
This PR adds a `pragma[noopt]` to force the current join ordering for the `guards` predicate in the `DataFlowUtil` library. This is necessary because of an upcoming change to the optimiser (computing size estimates for `newtype`s) that will unfortunately lead to a bad choice of join ordering in this case.
cc. @github/codeql-core
> Performance: Fix bad join ordering

- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
As @adityasharad pointed out on Slack, my solution of adding `pragma[noopt]` on https://github.com/github/codeql-go/pull/547 was perhaps a bit too drastic a way to get the right join order. This changes to use `pragma[only_bind_into]` instead, which means that other potential optimisations that the compiler might want to do will not be inhibited, and we still get the desired join order with the new optimiser.
cc. @github/codeql-core
> Performance: Remove `pragma[noopt]`

- ql/src/codeql-suites/go-developer-happiness.qls
These are the queries added in https://github.com/github/codeql-go/pull/558.
Note that when the qlpack name changes, this suite will need updating.
I wasn't sure if this was testable prior to merging, so any suggestions there welcome.
> Add a query suite for new experimental "developer happiness" queries

- extractor/extractor.go
- extractor/util/util.go
> Accelerating go-extractor by using 'go list -deps' instead of just 'go list'

- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
This fixes a case seen in a customer POV where evidently sufficient functions had a lot of return instructions (or other output nodes) that the `not exists(DataFlow::Node otherRet | otherRet != ret)` construct, which compiles to a cartesian product of the output nodes, filtration and set subtraction, was too expensive. Dist-compare forthcoming.
> Use unique aggregate to optimize guardingFunction

- codeql-extractor.yml
- codeql-tools/pre-finalize.cmd
- codeql-tools/pre-finalize.sh
With [CodeQL 2.6.2](https://github.com/github/codeql-cli-binaries/releases/tag/v2.6.2) this is now the default behavior, and the environment variable is therefore no longer needed.
> Remove `CODEQL_REDUCE_FILES_FOLDERS_RELATIONS`

- ql/src/experimental/CWE-942/CorsMisconfiguration.ql
A wildcard origin does not allow Access-Control-Allow-Credentials: true.
This change had been made in https://github.com/github/codeql-go/commit/824b5a4b52b92859b4963f702b3c117e729b815e
but I has been forgotten to update the query description.
CC:@gagliardetto
> Update query description

- ql/src/AlertSuppression.ql
- ql/src/Diagnostics/DiagnosticsReporting.qll
- ql/src/semmle/go/StringOps.qll
- ql/src/semmle/go/VariableWithFields.qll
- ql/src/semmle/go/controlflow/BasicBlocks.qll
- ql/src/semmle/go/controlflow/ControlFlowGraph.qll
- ql/src/semmle/go/controlflow/IR.qll
- ql/src/semmle/go/dataflow/GlobalValueNumbering.qll
- ql/src/semmle/go/dataflow/SSA.qll
- ql/src/semmle/go/dataflow/internal/DataFlowImpl.qll
- ql/src/semmle/go/dataflow/internal/DataFlowImpl2.qll
- ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
- ql/src/semmle/go/frameworks/stdlib/HtmlTemplate.qll
Port of https://github.com/github/codeql/pull/6775
> Fix `hasLocationInfo` URL reference

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- change-notes/1.24/analysis-go.md
- change-notes/2020-12-08-k8s-io-apimachinery-pkg-runtime.md
- ql/docs/experimental.md
- ql/test/library-tests/semmle/go/frameworks/Revel/examples/README.md
Was working on [CTF Go and don't return](https://securitylab.github.com/ctf/go-and-dont-return/) and hit a few broken links along the way, namely [QL](https://help.semmle.com/QL/) and [CodeQL CLI](https://help.semmle.com/codeql/codeql-cli.html) from the README of the repo, looks like quite a few of the semmle pages have disappeared. 
Wrote a script to find all links in `.md` files with non-200 response status codes, and fixed those to all be 200.
Original script results before these changes was:
```
[301]  codeql-go/CODE_OF_CONDUCT.md -> https://www.contributor-covenant.org/version/1/4/code-of-conduct.html
[301]  codeql-go/CODE_OF_CONDUCT.md -> https://www.contributor-covenant.org/faq
[301]  codeql-go/README.md -> https://help.semmle.com/QL
[404]  codeql-go/README.md -> …
```
> Fixed broken/moved/redirected links.

- codeql-tools/osx64/compiler-tracing.spec
As outlined in https://github.com/github/semmle-code/pull/40797, we do not need these stanzas anymore.
> Remove macos compatibility stanzas from tracing config.

- codeql-tools/tracing-config.lua
There have been some updates to the Lua tracing API, this converts the `tracing-config.lua` to follow these API changes.
> Update tracing-config.lua to newest API.

- ql/lib/semmle/go/frameworks/SQL.qll
- ql/test/library-tests/semmle/go/frameworks/SQL/main.go
Add `Where` method of builders for sql query sinks. `Where` is a vulnerable sink if tainted input of `string` type ends up in the first parameter. First parameter to `Where` is [typed as](https://github.com/Masterminds/squirrel/blob/84ae2bc4a87a432b1400474f3d48dd08961ecf40/where.go#L9) `interface{}` but the current ql only considers when the parameter is of `StringType`.
- [SelectBuilder.Where](https://pkg.go.dev/github.com/Masterminds/squirrel#SelectBuilder.Where)
- [UpdateBuilder.Where](https://pkg.go.dev/github.com/Masterminds/squirrel#UpdateBuilder.Where)
- [DeleteBuilder.Where](https://pkg.go.dev/github.com/Masterminds/squirrel#DeleteBuilder.Where)
> Add `Where` method of squirrel sql builders to query range

- extractor/extractor.go
- ql/test/library-tests/semmle/go/Function/getParameter.expected
- ql/test/library-tests/semmle/go/Function/variadicFunctions.go
- ql/test/library-tests/semmle/go/Types/SignatureType_getNumParameter.expected
- ql/test/library-tests/semmle/go/Types/SignatureType_getNumResult.expected
- ql/test/library-tests/semmle/go/Types/variadicFunctions.go
This will fix a bug where non-variadic functions which have the same signature as a variadic function are erroneously considered as variadic.
Note that this PR clashes with https://github.com/github/codeql-go/pull/619. When one is merged the tests will have to be updated in the other.
> Update extractor to distinguish variadic and non-variadic signature types

- ql/lib/semmle/go/security/AllocationSizeOverflowCustomizations.qll
- ql/src/Security/CWE-209/StackTraceExposure.ql
- ql/src/Security/CWE-295/DisabledCertificateCheck.ql
- ql/src/Security/CWE-327/InsecureTLS.ql
- ql/src/experimental/CWE-942/CorsMisconfiguration.ql
The join order fix takes 10 seconds off that predicate; the get-a-flag changes take about 25% off compared to using regexes.
> Improve performance: join-order AllocationSizeOverflow's source and use `matches` not `regexpFind`

- ql/lib/semmle/go/frameworks/stdlib/DatabaseSql.qll
This error seems to have been introduced in
36bbf1eeb9d8674e0e27b4ce9dc21da7590d6df1
Docs: https://pkg.go.dev/database/sql#DB
> Fix incorrect type name in database/sql model

- ql/lib/semmle/go/dataflow/ExternalFlow.qll
- ql/lib/semmle/go/dataflow/internal/DataFlowNodes.qll
- ql/test/library-tests/semmle/go/dataflow/ExternalFlow/sinks.expected
- ql/test/library-tests/semmle/go/dataflow/ExternalFlow/steps.expected
- ql/test/library-tests/semmle/go/dataflow/ExternalFlow/test.go
This is needed so that the new models-as-data framework can be used to model flow through receivers.
> Allow data flow through receiver for modelled methods

- ql/src/change-notes/2021-12-14-strings-replace-sanitizers.md
There was a single change note that was added to the old change note directory right around the time we moved to using the new per-pack location.
> Move change notes to proper location

- ql/lib/semmle/go/frameworks/stdlib/Fmt.qll
- ql/test/query-tests/Security/CWE-117/LogInjection.go
In future we could try harder to find out whether you're Fprintf'ing to stdout, a file named xyz.log etc, but for now this causes Fprintf'ing to an HTTP writer to be mistaken for log-injection rather than just XSS.
> Declassify fmt.Fprintf as a log sink

- extractor/cli/go-autobuilder/go-autobuilder.go
This makes source locations consistent between databases that do and don't use the `SEMMLE_PATH_TRANSFORMER` option in the case where the original source location isn't its own realpath (i.e, some parent directory is a symbolic link).
This can't be tested with a qltest since they can't use path rewriting. I will test this with a dist-compare run instead. It can also be informally tested by observing that if we have source dir `/a` which is a symlink to `/b`, an extraction without `LGTM_INDEX_IMPORT_PATH` or `GITHUB_REPOSITORY` set will result in source locations described relative to `/b`, whereas an extraction with one of those variables set will describe source locations relative to `/a` before this patch or to `/b` afterwards.
This caused results to go missing because their source …
> Path transformer: use fully resolved path

- .github/workflows/codeqltest.yml
This shouldn't fail, but currently does due to a bug and is unnecessary in any case.
> Don't use codeql pack install --verify

- ql/lib/semmle/go/frameworks/SystemCommandExecutors.qll
- ql/lib/semmle/go/security/OpenUrlRedirectCustomizations.qll
- ql/lib/semmle/go/security/SensitiveActions.qll
- ql/src/InconsistentCode/LengthComparisonOffByOne.ql
- ql/src/experimental/CWE-327/CryptoLibraries.qll
and simplify an `any(..)` that was redundant.  
I've been patching `github/codeql` again, and I thought that you guys shouldn't miss out.
> use more set literals

- ql/lib/semmle/go/dataflow/internal/FlowSummaryImpl.qll
- ql/lib/semmle/go/dataflow/internal/FlowSummaryImplSpecific.qll
The way that `ReturnValue[n]` was supported in https://github.com/github/codeql-go/pull/574 involved editing some files that will be overwritten when the data flow libraries are next synced. We move this code from `FlowSummaryImpl.qll` into `FlowSummaryImplSpecific.qll` to avoid this problem.
We also add special treatment of `ReturnValue[n]` in one place where it was missing.
> Refactor `ReturnValue[n]` in data flow libraries

- ql/examples/snippets/incompleteswitchoverenum.ql
I worked on this for an internal query but it ended up being covered by a linter rule. However, it's simple enough that it might make an interesting example.
> Add an example query for inexhaustive switches

- ql/lib/semmle/go/frameworks/SQL.qll
You can import [Masterminds/squirrel](https://github.com/Masterminds/squirrel) as `gopkg.in/Masterminds/squirrel.v1`.
This was removed in 2018 from the README (https://github.com/Masterminds/squirrel/commit/d13326f0be730e8aa260f440b63fd00c858a03d0) but was previously the recommended method.
This PR adds that path to the matched packages for SQLI queries.
> Match gopkg.in import of squirrel for SQLi query

- .github/workflows/codeqltest.yml
Tracer appears to not yet support win2022
> CI: Run on Windows 2019

- ql/lib/semmle/go/dataflow/internal/FlowSummaryImpl.qll
- ql/lib/semmle/go/dataflow/internal/FlowSummaryImplSpecific.qll
- ql/test/library-tests/semmle/go/dataflow/ExternalFlow/completetest.ql
- ql/test/library-tests/semmle/go/dataflow/ExternalFlow/sinks.expected
- ql/test/library-tests/semmle/go/dataflow/ExternalFlow/sinks.ql
- ql/test/library-tests/semmle/go/dataflow/ExternalFlow/test.go
- ql/test/library-tests/semmle/go/dataflow/ExternalFlow/vendor/github.com/nonexistent/test/stub.go
I was trying to do a Go version of https://github.com/github/codeql/pull/7878, but it seem the `FlowSummaryImpl.qll` file is out of sync with `github/codeql`.
This updates the `FlowSummaryImpl.qll` to the version currently on `github/codeql`, and manually adds the need classes and predicates to `FlowSummaryImplSpecific.qll`.
> Go: sync FlowSummaryImpl.qll

- ql/lib/semmle/go/dataflow/internal/DataFlowNodes.qll
The qldoc of the predicate `isParameterOf` mentions the parameter `fd` that does not exists and is possible replaced by `c`
> Address incorrectly referenced parameter in QLdoc

- ql/lib/change-notes/2022-04-08-fix-global-dataflow.md
- ql/lib/semmle/go/dataflow/internal/DataFlowDispatch.qll
- ql/lib/semmle/go/dataflow/internal/DataFlowNodes.qll
- ql/lib/semmle/go/dataflow/internal/DataFlowPrivate.qll
The motivation is so that getEnclosingCallable() can cope with
nodes that are not in a callable.
> Extend DataFlowCallable to include file scopes

- ql/lib/xml.dbscheme
https://github.com/github/codeql-go/pull/560 follow-up.
> Drop redundant columns from `files` and `folders` relations in `xml.dbscheme`

- extractor/cli/go-autobuilder/go-autobuilder.go
I think this works. The easiest way to test it is to delete lines from go.mod and/or go.sum and check that it works and prints log messages that make sense.
> Run `go mod tidy -e` before building

- ql/lib/semmle/go/frameworks/SQL.qll
- ql/test/library-tests/semmle/go/frameworks/SQL/go.mod
- ql/test/library-tests/semmle/go/frameworks/SQL/main.go
- ql/test/library-tests/semmle/go/frameworks/SQL/vendor/github.com/Masterminds/squirrel/stub.go
- ql/test/query-tests/Security/CWE-089/go.mod
- ql/test/query-tests/Security/CWE-089/vendor/github.com/Masterminds/squirrel/stub.go
- ql/test/query-tests/Security/CWE-089/vendor/modules.txt
Building on @tunnelshade's work in #611, add a few additional methods with similar signatures/issues.
These are vulnerable sinks if the first parameter is tainted input.
Some of these functions accept `interface{}` type in which case only `string` type (`StringType`) is tainted/vulnerable.
* [SelectBuilder.Column](https://pkg.go.dev/github.com/Masterminds/squirrel#SelectBuilder.Column)
* [SelectBuilder.From](https://pkg.go.dev/github.com/Masterminds/squirrel#SelectBuilder.From)
* [SelectBuilder.JoinClause](https://pkg.go.dev/github.com/Masterminds/squirrel#SelectBuilder.JoinClause)
* [SelectBuilder.LeftJoin](https://pkg.go.dev/github.com/Masterminds/squirrel#SelectBuilder.LeftJoin)
* [SelectBuilder.RightJoin](https://pkg.go.dev/github.com/Masterminds/squirrel#SelectBuilder.RightJoin)
* …
> Add Column, From, JoinClause, *Join, Having, OrderByClause methods for squirrel SQLi query

- ql/lib/semmle/go/frameworks/SQL.qll
- ql/test/library-tests/semmle/go/frameworks/SQL/go.mod
- ql/test/library-tests/semmle/go/frameworks/SQL/main.go
- ql/test/library-tests/semmle/go/frameworks/SQL/vendor/github.com/Masterminds/squirrel/stub.go
- ql/test/query-tests/Security/CWE-089/go.mod
- ql/test/query-tests/Security/CWE-089/vendor/github.com/Masterminds/squirrel/stub.go
- ql/test/query-tests/Security/CWE-089/vendor/modules.txt
Reverts github/codeql-go#682.
Accidentally automerged due to changing required checks.
> Revert #682
